### ISSUE TITLE
Customizer does not open in app for Business Plan sites with plugins installed

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-desktop#371] opened 2017-11-18 00:08 UTC
<blockquote>Customize – while Free and Premium plans Customizer are both loading on the app, Customizer for [Business Plan sites with plugins installed] will open in default browser.</blockquote>

/hat tip Rose's original report at  p5T066-ya-p2 #comment-1123

**Comment by designsimply** [comment] 2017-11-18 00:08
Tested and confirmed using WPDesktop 3.1.0-beta2 on Mac OS X 10.12.6.

**Comment by rachelmcr** [comment] 2017-11-18 18:51
This is expected, as Atomic and Jetpack sites don't open the customizer in Calypso; the customizer is opened in a new window in WP Admin (so the desktop app has to open it in a browser).

**Comment by rachelmcr** [comment] 2018-10-24 09:45
Closing as this is the expected behavior (not a bug).

**Closed by rachelmcr** 2018-10-24 09:45 UTC
Labels: [Type] Bug
