### ISSUE TITLE
Error: getaddrinfo EAI_AGAIN wordpress.com:443

### ISSUE THREAD

**Issue by orschiro** [Automattic/wp-desktop#196] opened 2016-06-09 19:43 UTC
Dear all, 

I would like to let you know that the app crashed with the following error message:

```
Please restart the app and try again.

If you continue to have issues, please contact us at help@wordpress.com and mention the error details below:

Error: getaddrinfo EAI_AGAIN wordpress.com:443
    at Object.exports._errnoException (util.js:856:11)
    at errnoException (dns.js:31:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)

System info: {"platform":"linux","release":"4.4.0-22-generic","version":"1.3.4-alpha1","build":"release"}
```

Thankfully,

~Robert

**Comment by designsimply** [comment] 2016-06-10 03:40
Thanks for the note @orschiro. Did restarting the app resolve the problem in this case?

**Comment by orschiro** [comment] 2016-06-10 05:15
Dear Sheri,

Indeed, restarting the app resolved the problem.

I still thought it might be worth and valuable sharing this error with you.
:-)

Warmly,

~Robert

**Comment by yxf007** [comment] 2018-10-10 07:39
To no avail

**Comment by nsakaimbo** [comment] 2020-02-21 21:30
Closing this issue as this hasn't been encountered during testing since it was initially reported (and no updates have been made since). At the very least, a report of the user's actions just prior to the crash would be useful to reproduce.

**Closed by nsakaimbo** 2020-02-21 21:30 UTC
Labels: OSS Citizen, [Type] Bug
