### ISSUE TITLE
Cannot access block editor via the app when using either a WordPress.com Atomic or a Jetpack site

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-desktop#640] opened 2019-06-26 06:18 UTC
We have two situations, yet the block editor isn't working in the app.

1. On a Business plan site on WordPress.com

#### Steps to reproduce
1. Try to change the editor to Classic, if you're on the Block one and then back to the Block editor.

#### What I expected
To be able to use the Block editor

#### What happened instead
The page just refreshes and hides the sidebar.

2. On a self-hosted site(tested with Jurassic ninja)

#### Steps to reproduce
1. Create a new site -> Connect it to Jetpack.
2. Select a post or a page and try to switch to the Block editor
3. The page within the app will sort of freeze and open a new one in the browser
4. Click back to return to the page/post list and try to enter again one of them in order to edit it

#### What I expected
To be able to use the Block editor in the app

#### What happened instead
It will redirect you to the browser in order to edit your content.

#### App Version / OS version
WordPress 4.2.0 / MacOS 10.14.5

#### Screenshot / Video
https://monosnap.com/file/wgDgF02nQuGRN8hKrT9VGt2uTer4MK

#### Context / Source
#user-report #manual-testing

#2135575-zen

**Comment by rachelmcr** [comment] 2019-06-26 10:50
Thanks for the report! I confirmed that on a WordPress.com Atomic site, the app consistently redirects to the Calypso classic editor, regardless of the block editor setting/switch. The block editor switch works for WordPress.com Simple sites as expected.

We're in a bit of an in-between stage with the desktop app. The block editor in Calypso is supported for Jetpack/Atomic sites on the web, but it isn't yet enabled in the app. You can refer to Automattic/wp-calypso#32048 for progress on enabling that in the desktop app.

The current behavior might be what's expected for Atomic sites at the moment, although I'm not sure. The other behavior you described (with a Jetpack site) is currently the expected behavior for Jetpack sites (since the block editor isn't supported in the app, it opens in a browser tab instead). @apeatling should the behavior for Atomic and Jetpack sites be the same in the app right now (either both forced to use the classic editor, or both opening the block editor in a browser)?

**Comment by SiobhyB** [comment] 2019-07-02 13:40
This came up again in 2144735-zen. The user has an Atomic site and would like to use the new block editor in the desktop app, but they're not able to load it.

**Comment by designsimply** [comment] 2019-07-10 18:49
Tested and confirmed that I cannot use the block editor for Atomic or Jetpack sites in WPDesktop 4.3.0-beta1. 

Trying to edit a post on a Jetpack site via WPDesktop 4.3.0-beta1 opens a browser window instead.

Trying to edit a post on an Atomic site via WPDesktop 4.3.0-beta1 fails silently and reverts to the classic editor. There are LOTs of prompts to try the block editor though! ([1m47s](https://cloudup.com/cxZyLR0by_V))

**Comment by designsimply** [comment] 2019-07-10 19:00
Raising to high priority because it came up for the last two beta testing sessions and because there are user reports noted on the issue.

**Comment by apeatling** [comment] 2019-07-10 19:11
@gwwar With the spinning out of two folks to concentrate plugins and the integration backlog, where could this realistically fall in terms of prioritization? I ask since it's been flagged in the beta sessions and user reports.

**Comment by gwwar** [comment] 2019-07-10 19:16
This is a medium-size project to resolve the API opt-in vs Classic Editor plugin, but it can be prioritized if we're given the focus and space to complete this.

**Comment by apeatling** [comment] 2019-07-10 19:22
I think prioritizing it relative to the other integration issues in the backlog would be best, based on user impact.

**Comment by designsimply** [comment] 2019-07-11 18:19
Extra notes: 

* Edit Focus Support Squad plans to review this issue after the squad convenes on July 29th. 
* Other high priority WPDesktop block editor issues can be submitted at that time for prioritization by the squad.

<sub>(internal reference: paAmJe-Ae-p2 cc @kwight)</sub>

**Comment by helmutgranda** [comment] 2019-07-16 17:32
Is there any way to reset back to Classic? I don't mind using Classic while this bug is being worked on.

**Comment by nagpai** [comment] 2019-07-17 07:45
Came up on 2161172-zd

User on Windows 8.1 pro  64 bit - Atomic Site.

**Comment by mattwiebe** [comment] 2019-07-23 16:03
I wonder if #34833 will fix this?

**Comment by mmtr** [comment] 2019-07-24 05:16
You're right @mattwiebe. I just merged that PR, so that should solve this issue for the next version of the desktop app. Should we keep this issue open until then?

**Comment by mattwiebe** [comment] 2019-07-24 15:09
> Should we keep this issue open until then?

Seems good to me. Glad that it fixes it. :)

**Comment by AashikP** [comment] 2019-07-27 05:30
Also reported in 2210227-zen. Thank you for the fix @mmtr

**Comment by mmtr** [comment] 2019-08-13 01:49
Confirmed this is resolved in the second beta of 4.3.0.

Users can try out the beta version by going to the app menu under WordPress.com > Preferences and selecting "Beta" for the Release Channel. Restarting the app will trigger an update to the beta version.

**Comment by designsimply** [comment] 2020-04-03 22:52
Re-opening because I found this problem is happening for me again after testing with WPDesktop 5.0.0 and 5.0.1-beta2. I would consider this a blocker. cc @nsakaimbo @belcherj @loremattei 

1. Setup up a WordPress site.
1. Install, activate, and connect the Jetpack plugin (I used the Jetpack Install flow on the WP mobile app, noting it in case it turns out to be relevant).
1. Install and activate the Classic Editor plugin.
1. Create a few posts using the classic editor.
1. Deactivate the Classic Editor plugin.
1. Install WP Desktop 5.0.0.
1. Log in to the WP Desktop app using the Jetpack-connected account for the site.
1. Try to create a new post on the Jetpack-connected site using the WP Desktop app.

**Result:** whenever I try to create or open a post using the block editor on a Jetpack site in the WP Desktop app, I am redirected to the web instead. This results in a stuck placeholder image in the app that cannot be resolved by closing/re-opening or by deleting/re-installing the WP Desktop app. ([3m52s](https://cloudup.com/cYrDAk9N4jf), [8m21s](https://cloudup.com/cb19VM-m1Uj))

![blank-editor-placeholder-screen-in-wpdesktop-5 0 1-beta2](https://user-images.githubusercontent.com/1119271/78404122-fac80200-75ba-11ea-88a5-0b78d17f720e.png)
<p style="clear:both;"><sup>Tested with WPDesktop 5.0.1-beta2 on macOS 10.14.6 on a site running WP 5.4 Jetpack 8.3 with and without the Classic Editor 1.5 plugin activated.</sup></p>

**Temporary workarounds:** to get out of the stuck editor showing only the placeholder in the app, you can either activate the Classic Editor plugin on the site or you can delete `~/Library/Application\ Support/WordPress.com/settings.json` to be able to re-open the app but the editor problem will recur if you try to open or create a post with the block editor

**Comment by nsakaimbo** [comment] 2020-04-03 22:54
Thanks for the repro, @designsimply! This is super helpful.

**Comment by formosattic** [comment] 2020-04-21 04:09
Reported in 2890872-zen, and was able to reproduce issue, with version 5.1.0-beta1.

<img width="1111" alt="Screen Shot 2020-04-21 at 12 08 11" src="https://user-images.githubusercontent.com/15944096/79824454-d34da380-83c8-11ea-8c2f-7ab70a1dcc08.png">

**Comment by nsakaimbo** [comment] 2020-04-29 15:01
Here's a recap of debugging efforts so far:

**Repro**: @designsimply found that this bug is triggered 100% of the time for self-hosted sites (connected via JetPack).

I've spent the last few days trying to trace this, and here's what I've found so far:

- When "new post" is clicked, this triggers the series of callbacks for the route `/block-editor/post/:site/:post?` in the `gutenberg/editor` module: ([L29-35](https://github.com/Automattic/wp-calypso/blob/c0a21e929c970ca8d9d585047456f183cdbe54a2/client/gutenberg/editor/index.js#L29-L35))
- There's a few places within this series of callbacks that _may_ redirect to the WP Admin login prompt. I added some ad-hoc debugging and confirmed the redirect isn't happening until the [`post`](https://github.com/Automattic/wp-calypso/blob/a234c0704601a01a812f1a7a167f571593bbc763/client/gutenberg/editor/controller.js#L168-L202) callback where the Calypso iframe component is invoked.
  - Within `calypsoify-iframe.tsx`, the redirect to WP Admin occurs because of a timeout on [L568](https://github.com/Automattic/wp-calypso/blob/c0a21e929c970ca8d9d585047456f183cdbe54a2/client/gutenberg/editor/calypsoify-iframe.tsx#L567-L570):
  ```
  if ( finishCondition === 'timeout' ) {
    window.location.replace( iframeUrl );
    return;
  }
  ```
  - At this point, `iframeUrl` is set to `.../wp-admin/post-new.php?`, which is configured on lines [686-689](https://github.com/Automattic/wp-calypso/blob/c0a21e929c970ca8d9d585047456f183cdbe54a2/client/gutenberg/editor/calypsoify-iframe.tsx#L686-L691).
  - However, when the redirect from this snippet is fired, the URL in the browser is `.../wp-login.php?redirect_to=...wp-admin/post-new.php?...`
      - I cannot find where in the `CalypsoifyIframe` component this redirect is generated (i.e. there doesn't appear to be any code to generate the Admin login URL with a redirect in this file)
      - The redirect looks suspiciously identical to [this block](https://github.com/Automattic/wp-calypso/blob/a234c0704601a01a812f1a7a167f571593bbc763/client/gutenberg/editor/controller.js#L109-L128) of code by the `authenticate` handler for the route, but I have confirmed this has nothing to do with this particular issue (in fact, I went so far as to comment out this block of code in `authenticate` entirely, and the redirect still happened!)

**Question**: I'm trying to understand why/how, if the user is already logged into the Desktop app, does the `Calypsoify` component end up sending them to log in via WP Admin login? What could be missing here?

@griffbrad Any thoughts/pointers here, or perhaps a suggestion on who might be a good resource that might have a better handle on this logic? (I understand @creativecoder might be taking a look at this soon, but happy to keep pushing on this in the mean time with some help.)

cc: @noahtallen (thanks for the pointers so far, just an FYI in case the above sparks any insight)

FYI: @belcherj

**Comment by nsakaimbo** [comment] 2020-04-29 19:13
**Update**: Going to start looking into how the desktop facilitates authorization of external iframe content. The fact that the app cannot load the customizer for Jetpack-enabled sites (#865) smells  like a potentially common root cause.

**Comment by nsakaimbo** [comment] 2020-05-01 19:46
After a little more debugging, I've been able to determine that the cause of the redirect isn't Calypso, it's Jetpack in the self-hosted/remote site. In summary:

- Calypso is working correctly in this scenario and sends the user to the URL `...wp-admin/post-new.php?...`
- When the desktop app attempts to navigate to this URL, the self-hosted Jetpack instance responds with a redirect to log into the site's admin `.../wp-login.php?redirect_to=...wp-admin/post-new.php?...` _because the self-hosted site's cookies are not present in the prior request_ (i.e. the desktop app doesn't have/know anything about the cookies required by the remote site)

**Note**: this exact behavior will also occur in a browser that has not previously been logged into the self-hosted site, not just the desktop app.

**Workaround**

To work around this, the `jetpack_sso_bypass_login_forward_wpcom` toggle must be activated in the self-hosted site's Jetpack WP Admin settings:

<p align="center">
<img width="531" alt="self-hosted-SSO" src="https://user-images.githubusercontent.com/8979548/80836083-0874a580-8bc2-11ea-8430-bad7fba0c334.png">
</p>

When the user attempts to use Gutenberg in the self-hosted site, it will work as expected without the user having to authenticate via `wp-admin`.

This is great, but admittedly not the greatest user experience. Users have to know _in advance_ to have the Single Sign-On toggled in Jetpack. At the very least, this requirement should be made more explicit within the desktop app, even better if we could make the transition more seamless and have it "just work" without the user having to take any action. Still exploring/brainstorming solutions...

Thanks @ebinnion for helping shed some light here!

FYI: @designsimply

**Comment by creativecoder** [comment] 2020-05-05 19:11
FYI @Automattic/explorers , as this will be something we need to consider for the [WordPress.com editor deprecation](https://github.com/Automattic/wp-calypso/milestone/309) when redirecting users to the Classic editor in wp-admin.

**Comment by nsakaimbo** [comment] 2020-05-05 19:50
Thanks, @creativecoder.

The TL;DR here is that Jetpack users have no way to use Gutenberg within the Desktop app unless they enable SSO. They won't even be able to use the Classic Editor as a fallback because that will no longer be available as an option to them once the deprecation is complete.

I'm currently trying to wire up some messaging for Jetpack users effectively saying they have to enable SSO. This isn't ideal as it really breaks the user's experience, but while a more ideal solution is pending some additional messaging might help, at least.

cc: @Automattic/explorers

**Comment by nsakaimbo** [comment] 2020-05-29 20:48
The ability to enable SSO in-app and proceed to the editor has been added in #876 and Automattic/wp-calypso#42183. This should prevent Jetpack/self-hosted users from being left in a broken state when trying to use the Gutenberg editor.

**Closed by nsakaimbo** 2020-05-29 20:48 UTC
Labels: [Pri] BLOCKER, [Type] Bug
