### ISSUE TITLE
Notifications: @usernames break comment reply input

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-desktop#296] opened 2017-05-01 23:44 UTC
I tried responding to a comment, but when I attempted to type a username it broke the comment reply form. When I typed <code>@name</code> and then stopped typing I did not see any type-ahead suggestions (which may not affect non-a8c users too much), but I could also no longer type anything in the input. 

There isn't much to see in a screenshot, but: 

![image](https://cloud.githubusercontent.com/assets/437258/25598986/982b994e-2ea6-11e7-8ffe-568a6c680ed3.png)

There you can see there are no suggestions.

**Comment by designsimply** [comment] 2017-05-02 19:44
Thank you for reporting this! I tested with Safari 10.1 on Mac OS X 10.12.4 and was able to reproduce. I'm closing this report in favor of https://github.com/Automattic/wp-calypso/issues/11526 since the problem doesn't seem to be desktop-app-specific.

**Closed by designsimply** 2017-05-02 19:44 UTC
Labels: [Type] Bug
