### ISSUE TITLE
Please add auto-scroll while typing

### ISSUE THREAD

**Issue by brionz** [Automattic/wp-desktop#256] opened 2016-12-27 18:40 UTC
I installed the WordPress.com Desktop Apps when I am typing it **not** automatically scroll down, and cannot see my text/paragraph I type.

**Comment by lancewillett** [comment] 2017-02-03 17:23
Hello, could you please add your OS name and version, and the version of the app you're using? A screenshot or video would help a lot, too, to understand what you're expecting versus what's happening.

**Comment by rachelmcr** [comment] 2017-03-27 16:00
We recently received this feedback from a desktop app user:

> I like the new WordPress Desktop app, but it could be better. I would definitely like to see a typewriter mode feature so that a document automatically scrolls up as you type.

I tested on Mac OSX 10.12.3 with the desktop app beta version 2.3.0-beta3, and I couldn't reproduce this behavior. The editor scrolled down as I typed. It looks like this behavior may have been improved in Calypso as part of the recent editor improvements:

https://github.com/Automattic/wp-calypso/issues/11996#issuecomment-286479794

**Comment by mvuijlst** [comment] 2017-07-08 08:30
Version 2.7.0-beta1, Windows 10.

[See screencast](https://github.com/Automattic/wp-desktop/files/1132854/2017-07-08.10-26-45.zip): when you reach the bottom of the screen while typing, it takes two lines until the app jumps up half a screen.

**Comment by nsakaimbo** [comment] 2020-02-21 20:29
Tested with v5.0.0-beta2 and scrolling behavior when at the end of existing content seems to work reasonably well in both the Classic and Gutenberg editors. Closing this issue, but please feel free to re-open if you're still encountering this issue (or it re-occurs).

**Closed by nsakaimbo** 2020-02-21 20:29 UTC
Labels: OSS Citizen, [Platform] Windows, [Type] Bug
