### ISSUE TITLE
Windows :: Fatal Error w/ version 2.2.0

### ISSUE THREAD

**Issue by mdbitz** [Automattic/wp-desktop#273] opened 2017-02-24 15:17 UTC
![untitled](https://cloud.githubusercontent.com/assets/5784663/23308738/2855ed1e-fa7a-11e6-9807-e6b6a6ad2afb.png)

Hi everyone. I have reports from a user that version 2.2.0 of the Desktop is crashing unexpectedly. The above crash report is from the user. I'm trying to get additional details on the actions they were taking but wanted to make sure this got shared for review.

Thank you!

**Comment by hoverduck** [comment] 2017-02-27 16:18
Closing as duplicate of https://github.com/Automattic/wp-desktop/issues/248

**Closed by hoverduck** 2017-02-27 16:18 UTC
