### ISSUE TITLE
OSX: spell checking not working

### ISSUE THREAD

**Issue by BlameDutchie** [Automattic/wp-desktop#389] opened 2017-12-19 19:07 UTC
I know, spell checking is experimental, but doing absolutely nothing is not what I expected.

WPD 3.1.0 / macOS High Sierra 10.13.2

**Comment by rachelmcr** [comment] 2019-06-12 14:16
While testing on macOS 10.14.5, WPDesktop 4.2.0-beta1, I noticed that spell checking does not work consistently in the block editor (Gutenberg).

It works for me consistently in the classic Calypso editor, and sometimes in the block editor, but when the block editor includes special styles I don't see any spell checking:

![Screenshot 2019-06-12 15 05 06](https://user-images.githubusercontent.com/8658164/59358615-cc73f000-8d24-11e9-8308-535e91dc54bf.png)

That contrasts with the web browser, where the same post gets spell checking (highlighting misspelled words) as expected:

![Screenshot 2019-06-12 15 08 07](https://user-images.githubusercontent.com/8658164/59358711-f75e4400-8d24-11e9-989f-765d2394b034.png)

**Comment by nsakaimbo** [comment] 2020-02-19 17:48
Update: more reliable spellchecking across all platforms (Windows included) is part of a forthcoming update (v5.0.0) that includes an upgrade of Electron and core dependencies (see #757). Feel free to try the latest beta release (v5.0.0-beta2) to verify spellchecker behavior.

**Comment by rachelmcr** [comment] 2020-02-20 15:08
I tested the block editor in v5.0.0-beta2 on macOS 10.15.3, and I confirmed that the spellchecker is now underlining misspelled words as I expect (including on the site where I previously tested this behavior). Woohoo!

**Comment by nsakaimbo** [comment] 2021-06-30 18:46
Update on this thread: we're closing this issue as we expect this and a whole host of other issues to be resolved by the new version of the application (v7.0.5) that was just released. The latest build can now be downloaded at the WordPress Desktop landing page [here](P7jrAc-3-p2).

**Closed by nsakaimbo** 2021-06-30 18:46 UTC
Labels: OSS Citizen, [Type] Enhancement
