### ISSUE TITLE
Login: After logging out, my avatar still appears in the masterbar for signup

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-desktop#514] opened 2018-10-17 19:33 UTC
#### Steps to reproduce
1. Login to a WordPress.com account
2. Log out in the desktop app
3. Restart the desktop app
4. Click on the Create an Account link on the splash screen
5. Notice your avatar in the masterbar

#### What I expected
Not to see my avatar in the masterbar

#### What happened instead
I saw my avatar in the masterbar

#### App Version / OS version
3.6.0 / Mac

**Comment by rachelmcr** [comment] 2018-10-18 11:18
Thanks for reporting this! Closing it as a duplicate of https://github.com/Automattic/wp-desktop/issues/173.

**Closed by rachelmcr** 2018-10-18 11:18 UTC
Labels: [Type] Bug
