### ISSUE TITLE
Since Upgrade Can't Open Desktop app

### ISSUE THREAD

**Issue by jnthnmrgn** [Automattic/wp-desktop#213] opened 2016-07-28 10:55 UTC
I'm running OS X 10.11.6 and just upgraded to the latest version of the Wordpress.com Desktop app. 
Now every time I try and open the app the system dialogue tells me: 

> The application “WordPress.com” can’t be opened.

I've looked at my privacy settings and I can open software from Anywhere, so that's not the issue.

Thanks in advance for your help.

**Comment by markl181** [comment] 2016-07-31 02:01
I have the same issue since updating to 10.11.6. I tried removing and reinstalling, no luck. Here is the system error log message

Jul 30 19:59:39 Marks-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x1000002a.Electron[35834]): Could not find and/or execute program specified by service: 2: No such file or directory: /Applications/WordPress.com.app/Contents/MacOS/Electron
Jul 30 19:59:39 Marks-MacBook-Pro Finder[694]: spawn_via_launchd() failed, errno=111 label=[0x0-0x236b369].com.automattic.wordpress path=/Applications/WordPress.com.app/Contents/MacOS/Electron flags=1 : LaunchApplicationClient.cp #963 LaunchApplicationWithSpawnViaLaunchD() q=com.apple.root.default-qos
Jul 30 19:59:39 Marks-MacBook-Pro Finder[694]: spawn_via_launchd() failed, errno=111 label=[0x0-0x236b369].com.automattic.wordpress path=/Applications/WordPress.com.app/Contents/MacOS/Electron flags=1

**Comment by toddsattersten** [comment] 2016-08-01 16:16
Wanted to report the same trouble as the folks above.

**Comment by DragonBe** [comment] 2016-08-02 15:47
Installed latest version of Desktop app (can't find version number for it) from https://apps.wordpress.com, but getting above mentioned error

![screenshot 2016-08-02 17 40 23](https://cloud.githubusercontent.com/assets/282825/17335006/b2256b30-58d8-11e6-83f9-f037258868a7.png)

Also running Mac OS X 10.11.6

![screenshot 2016-08-02 17 40 46](https://cloud.githubusercontent.com/assets/282825/17335026/c4503f38-58d8-11e6-9446-36804a1aa8c5.png)

Hope this information helps.

**Comment by rachelmcr** [comment] 2016-08-03 11:47
Thank you for reporting this! We've released a new version of the app (version 1.4.0) that should resolve this issue. Please give it a try — you can download it here:

https://apps.wordpress.com/desktop/

**Comment by DragonBe** [comment] 2016-08-04 20:28
![screenshot 2016-08-04 22 26 46](https://cloud.githubusercontent.com/assets/282825/17417237/9cdcb146-5a92-11e6-86c3-31795cd9b184.png)

Sorry @rachelmcr, it didn't work for me :sad_panda:

**Comment by markl181** [comment] 2016-08-04 22:05
@DragonBe did you reboot after installing? I was getting the same error after the update, so I rebooted and it's now working. It did take a few minutes to verify on first open, but now seems to be working smoothly again. Thanks @rachelmcr!

**Comment by DragonBe** [comment] 2016-08-08 05:30
@markl181 No I did not reboot because I never needed to do so 😸 

After reboot all errors are gone and WordPress app runs perfectly, just as you described.

![screenshot 2016-08-08 07 24 33](https://cloud.githubusercontent.com/assets/282825/17470068/a85387c6-5d39-11e6-8cb6-eb1a842232fe.png)

Only thing I wonder is why is a **reboot** required in order to run an isolated app? Is the app requiring some settings that are only activated after a reboot? This gots me confused 😕

**Comment by markl181** [comment] 2016-08-08 21:59
I'm not an OS expert, but my experience has been that applications ported from Windows to OS X require reboots to update, and native apps usually don't. I'm not sure why though!

**Comment by rachelmcr** [comment] 2016-09-06 14:40
I'm going to go ahead and close this issue since updating/restarting is working. Thanks everyone!

**Closed by rachelmcr** 2016-09-06 14:40 UTC
Labels: OSS Citizen

**Comment by sendhil** [comment] 2016-09-07 22:06
So the reason rebooting fixes the issue is due to the fact that older versions of our app pointed to an executable with a different name and along the way I believe our updating of Electron changed the name of the executable. The reason this is important is because it seems like Apple's `cfprefsd`(which is used when running an app to figure out how to open it) caches the location of the executable. The cache is reset on reboot which is why a reboot fixes the issue.

**Comment by markl181** [comment] 2016-09-08 03:07
Interesting, thanks!
