### ISSUE TITLE
Theme tab broken

### ISSUE THREAD

**Issue by orschiro** [Automattic/wp-desktop#158] opened 2016-04-15 11:09 UTC
Dear all, 

I just noticed this glitch on the Theme tab using the latest version on Ubuntu Linux:

Thankfully,

~Robert

![image](https://cloud.githubusercontent.com/assets/170947/14559745/48405bd0-030b-11e6-8264-8fac102fb698.png)

**Comment by jasmussen** [comment] 2016-04-15 11:24
Hi, thanks for the report.

Can you reproduce this in the web version, i.e. www.wordpress.com?

**Comment by orschiro** [comment] 2016-04-15 15:11
Hi Joen,

Thank you for your reply!

No, I can't reproduce this problem in the web version using Chromium.

~Robert

**Comment by jasmussen** [comment] 2016-04-18 10:23
I am able to reproduce now, and it seems to be app-only, but not limited to Linux:

![screen shot 2016-04-18 at 12 18 25](https://cloud.githubusercontent.com/assets/1204802/14600987/ba25e6b0-055f-11e6-9319-0d492ad13040.png)

Steps to reproduce:

1. Open the WordPress desktop app
2. Navigate to the My Sites > Themes section
3. Quit the app. 
4. Relaunch the app. 

Notice how upon relaunching the app, the themes section is now broken. 

Digging into the web-inspector, it appears the main content `div` has these classes: 

```
wp layout is-group-undefined is-section-undefined focus-content has-no-sidebar
```

but it should have these:

```
wp layout is-group-sites is-section-stats focus-content
```

The discrepancies to notice are the two `undefined`'s, and the `has-no-sidebar`.

It's likely this is related to the state-restoring code we have. CC: @mjangda

**Comment by orschiro** [comment] 2016-04-18 12:01
Dear @jasmussen,

Thanks so much for tracing back the issue!

~Robert

**Comment by lancewillett** [comment] 2016-04-18 17:23
Good find @orschiro, thank you.

**Comment by hoverduck** [comment] 2016-04-20 18:46
Sounds like you've got the problem narrowed down, but FWIW I also hit this bug by opening and quitting the Customizer, without restarting the app itself:

![wp-desktop-158](https://cloud.githubusercontent.com/assets/7233112/14686410/8bff224e-0706-11e6-9639-38fe3ddd1270.gif)

**Comment by rachelmcr** [comment] 2019-03-06 11:57
I tested this again on macOS 10.14.3, WPDesktop 3.9.0 and can no longer reproduce the issue with either steps shared here (quitting the app on the Themes section or opening and quitting the Customizer).

Closing as resolved, but please comment here if you're still seeing it somewhere (e.g. Linux).

**Closed by rachelmcr** 2019-03-06 11:57 UTC
Labels: OSS Citizen, [Type] Bug
