### ISSUE TITLE
Desktop App "Log In" Button

### ISSUE THREAD

**Issue by Ralagris** [Automattic/wp-desktop#472] opened 2018-07-09 22:52 UTC
#### Steps to reproduce
1. launch WordPress desktop app on iMac
2. press the "Sign In" button at the top right
3. 
4.

#### What I expected
I expected to log into my account within the App and write/edit blog posts. 

#### What happened instead
A web browser tab opened with blank login and password fields; my web browser is already logged into the Web version of WordPress. I entered the login information in those blank fields. Desktop App is still logged out. Pressing the "Sign In" button again in the App does not log me in - another web browser app opens with blank login fields. App has been reinstalled several times. 

#### App Version / OS version
App version 3.3.0 / macOS High Sierra version 10.13.5

**Comment by adlk** [comment] 2018-07-20 08:24
Hey @Ralagris thanks for opening this issue. Can you please provide a screenshot of the page you see when you open the app?

**Comment by Ralagris** [comment] 2018-07-21 22:15
Hi @adlk , as requested. 

![screen shot 2018-07-21 at 4 12 45 pm](https://user-images.githubusercontent.com/41027525/43040429-0d730dfe-8d01-11e8-96a6-2b6adf456a2b.png)

**Comment by rachelmcr** [comment] 2018-07-31 11:36
This looks like the same issue reported here: https://github.com/Automattic/wp-desktop/issues/400

**Comment by Ralagris** [comment] 2018-08-01 22:51
@rachelmcr , thanks. I too tried the (CMD + ALT + i) & (CTR + Shift + i) and I didn't get the dev tool for the app.

**Comment by rachelmcr** [comment] 2018-10-17 09:51
Thank you for checking that! I was able to reproduce the issue, and to resolve it (to get back to the app's login screen) I deleted the app and the following directories:
- `~/Library/Application Support/WordPress.com`
- `~/Library/Caches/com.automattic.wordpress`
- `~/Library/Saved Application State/com.automattic.wordpress.savedState`

If you are using Finder, you may have to change the View Options to make the `~/Library` directory visible first.

I'm going to close this issue, as I've confirmed it's the same as #400 and we're tracking it there.

**Closed by rachelmcr** 2018-10-17 09:51 UTC
Labels: OSS Citizen, [Type] Bug
