### ISSUE TITLE
new install shows different languages

### ISSUE THREAD

**Issue by jasonbrown1965** [Automattic/wp-desktop#989] opened 2021-07-26 23:52 UTC
Installed wp desktop on win10 64bit with latest updates.
Installer worked, app opened
**English** UI asks for email
Click enter, next app page is in **Spanish**
Click back button, try again
Add email again, click enter, next app page is in ..**Korean**
Uninstalled, trying again
Happy to supply logs if needed

**Comment by jasonbrown1965** [comment] 2021-07-26 23:58
Okay, installed again
Now a different problem - log-in loop
App opens on UI for requesting log-in code-via-email
But the request email button remains greyed out (yes, even after email is entered)
![image](https://user-images.githubusercontent.com/11400799/127073842-9e113458-075a-4cee-808c-d37a26be1f45.png)
Clicking "Enter a password instead" leads app back to main log-in UI
![image](https://user-images.githubusercontent.com/11400799/127073965-33bc93b5-569d-4597-95fd-8b290cc7503d.png)
.. which loops back to greyed-out code-via-email UI

**Comment by nsakaimbo** [comment] 2021-07-27 17:27
@jasonbrown1965 Thank you for the report! A couple of quick clarifications/questions:

(1) Do you happen to be using a VPN? If for some reason your IP address is being bounced around to different regions, this may result in the language inconsistencies you're observing.

(2) From what we can tell, it looks like you signed up for a "passwordless" account when you created your WordPress account. The desktop application does not support magic links via email at the moment. You would need to sign into WordPress on the web, add a password to your account, and then try to log back into the Desktop application with the newly-created password.

**Comment by belcherj** [comment] 2021-12-13 18:25
Closing as non-reproducible.

**Closed by belcherj** 2021-12-13 18:25 UTC
