### ISSUE TITLE
Problème avec "Afficher le site"

### ISSUE THREAD

**Issue by bryx** [Automattic/wp-desktop#366] opened 2017-11-13 20:00 UTC
Bonjour,

I don't speak English, sorry.

J'informe les développeurs que dans "Afficher le site" il y a un bug où la toolbar ne s'affiche pas et que le javascript en version responsive n'est pas possible. Je dois aller dans une catégorie pour que la toolbar s'affiche et que le bug s'efface temporairement.

Merci =)

**Comment by nsakaimbo** [comment] 2020-02-24 16:00
Translation (from Google Translate):

> I inform the developers that in "Display the site" there is a bug where the toolbar does not appear and that javascript in responsive version is not possible. I have to go to a category so that the toolbar is displayed and the bug is temporarily cleared.

In my testing, I have not encountered an issue resembling this description. Closing this issue given how much Calypso has changed since this report. However, please feel free to re-open if the issue is encountered again. We would likely need more details in order to reproduce.

**Closed by nsakaimbo** 2020-02-24 16:00 UTC
Labels: OSS Citizen, [Type] Bug
