### ISSUE TITLE
WordPress.com ran into an error! (code 105)

### ISSUE THREAD

**Issue by gellenburg** [Automattic/wp-desktop#334] opened 2017-09-28 23:26 UTC
* WordPress.com 2.8.0
 * Windows 10 15603

Everything was working fine under WordPress 2.7.1 (last version I used). Went to launch 2.7.1 and received:

> WordPress.com ran into an error! (code 105)

Was also notified that there was an update, so I downloaded 2.8.0.

Same thing.

Uninstalled 2.8.0.

Reinstalled 2.8.0.

Same thing.

I can login to WordPress.com with my account just fine, so this is localized to Calypso.

Thoughts?

**Comment by alisterscott** [comment] 2017-09-28 23:52
Hello @gellenburg - sorry to hear you're having some issues.

Could you please try uninstalling the app, and removing these files:

**Comment by gellenburg** [comment] 2017-09-29 00:27
Uninstalled.

The folder is no longer on my drive (so couldn't delete something that's no longer there):

```
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\gellenburg.WIN10SS>cd AppData

C:\Users\gellenburg.WIN10SS\AppData>cd Roaming

C:\Users\gellenburg.WIN10SS\AppData\Roaming>dir *word*
 Volume in drive C is Local Disk
 Volume Serial Number is 18AC-2B57

 Directory of C:\Users\gellenburg.WIN10SS\AppData\Roaming

File Not Found

C:\Users\gellenburg.WIN10SS\AppData\Roaming>
```

Reinstalled. The directory is now there:

```
C:\Users\gellenburg.WIN10SS\AppData\Roaming>dir *word*
 Volume in drive C is Local Disk
 Volume Serial Number is 18AC-2B57

 Directory of C:\Users\gellenburg.WIN10SS\AppData\Roaming

09/28/2017  08:23 PM    <DIR>          WordPress.com
               0 File(s)              0 bytes
               1 Dir(s)  1,763,195,777,024 bytes free

C:\Users\gellenburg.WIN10SS\AppData\Roaming>
```

Logging in (again).....

I see the page start to draw. I see the blue W in the circle on the white background then very quickly the page refreshes to a solid blue page with the following:

![2017-09-28 20_25_54-wordpress com failed to start](https://user-images.githubusercontent.com/7026750/30995951-4f9e8e06-a48b-11e7-9505-8af9d2cd2065.png)

And for the record, no I'm not using any type of proxy.

**Comment by gellenburg** [comment] 2017-09-29 19:33
Can somebody please change this to a bug? It's certainly not "a question". Thanks!

**Comment by alisterscott** [comment] 2017-10-02 22:38
hi @gellenburg: I've tried a few times on different Windows 10 machines and I can't reproduce this issue - could you try again or try using a different wifi or network connection?

**Comment by gellenburg** [comment] 2017-10-02 22:48
What is error code 105?

I only have one wifi. Running WordPress on my SurfaceStudio. It's not exactly "portable".

One WiFi. Google WiFi WAP/ Router. Comcast Business Internet.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by rachitpatel** [comment] 2017-12-14 11:29
This issue is also occurring on Mac version as well as of today. I just installed a fresh copy, tried to log in and first screen is with this error.

**Comment by lordofscripts** [comment] 2017-12-15 16:56
I am having this problem since the beginning of the week. This same installation was working fine last week! I am on Windows 7 Ultimate 64-bits.

I reinstalled but the issue was not gone. I then killed all three WP processes in order to be able to remove the Roaming\Wordpress.com folder which I removed subsequently. Then opened the WP app again on Windows but still got the Error Code 105.

I can login without problem using the web browser as well as with the Android app. How long until this gets solved?

**Comment by designsimply** [comment] 2017-12-15 17:43
<blockquote>This issue/bug is also occurring on Mac version as well as of today.</blockquote>

I just tested with WPDesktop 3.1.0 on Mac OS X 10.13.1 and was able to load the app and log in to several different types of accounts (Jetpack, WordPress.com, WordPress.com Business Plan) without any problems. I will test on Windows 10 next. In the mean time, may I please ask anyone having trouble with this issue to confirm you have tested with the latest version of the WordPress.com for Desktop app which is 3.1.0 at this time? May I also ask which version of the Jetpack plugin you are currently running? To be clear, do I understand correctly that you can open the app and see the login screen and that the problem only happens after you enter login details and click the "Sign in" button?

**Comment by rachitpatel** [comment] 2017-12-15 22:21
@designsimply 
👍 
The proxy setting was missing.  It's funny that I need to add 127.0.0.1 after "*.local, 169.254/16," and everything back to normal. You can close the issue for MAC. 
I think the message needs to be updated stating that "Make sure you have 127.0.0.1" under Proxies tab on MAC in order for this work." _for better user experience_.

**Comment by designsimply** [comment] 2017-12-16 01:33
@gellenburg and @lordofscripts, are you using a proxy for internet traffic by chance?

**Comment by drobertson123** [comment] 2017-12-19 17:03
This issue is still happening on Windows 10 Version 3.1.0 release.

I am not using any proxy of any type and the issue started happening recently. It was working fine before and I have not changed any network settings for months.

This has me completely down and is really messing up our publication schedule. Any idea what is going on?

**Comment by ema1982** [comment] 2017-12-22 19:53
I have a Mac and I am getting this same error.  I have the latest version - 3.1.0

My mac specs:

macOS High Sierra 10.13.2
2.4 GHz Intel Core i5
4 GB RAM

**Comment by rachitpatel** [comment] 2017-12-22 20:36
@ema1982, what’s in your proxy setting?

**Comment by ema1982** [comment] 2017-12-22 20:38
I have this under Auto Proxy Discovery:

*.local, 169.254/16, 127.0.0.1

I added the  , 127.0.0.1

**Comment by fabiofiss** [comment] 2017-12-25 15:33
Getting the same error on a Mac. Tried changing the proxy settings with no success.

**Comment by rachitpatel** [comment] 2017-12-25 15:41
I suggest you remove the app and reinstall clean if you haven't already. On MAC, I can't replicate after adding the proxy. Attached is my setting. Make sure it matches. I have no other clue at this point. 
<img width="659" alt="screen shot 2017-12-25 at 10 37 51 am" src="https://user-images.githubusercontent.com/758895/34341192-1b69b52e-e960-11e7-9ad8-bf31951bef03.png">

**Comment by OctoPenguin** [comment] 2017-12-27 08:42
I'm getting the error woth 3.1.0 on Windows too!

**Comment by ema1982** [comment] 2017-12-27 19:46
I tried uninstalling and reinstalling and I still get the same error.

**Comment by liuyigh** [comment] 2017-12-29 17:34
To people who have the same problem on Mac, try to reboot your computer after adding the proxy.

I have two mac having the problem. One iMac 2009 with 10.11.6. One MBP 2012 with 10.13.2. Still the same problem after adding the proxy. But both are fixed after reboot. Happy blogging now.

**Comment by OctoPenguin** [comment] 2018-01-03 15:32
I'm no longer getting this issue! If fixed itself (?)

**Comment by ema1982** [comment] 2018-01-03 23:48
Okay, I tried updating the proxy settings and then rebooted, and so far it's working okay.  I will keep an eye on it.

**Comment by OctoPenguin** [comment] 2018-01-04 11:27
My error is back! Let me try the proxy settings

**Comment by OctoPenguin** [comment] 2018-01-04 11:29
Right, so the workaround is definitely the proxy.

**Comment by ISNEYLER** [comment] 2018-01-10 16:05
the same thing happens to me I have windows 10 and wordpress 3.1.0
(I clarify that I do not speak English  I am using a translator)

![image](https://user-images.githubusercontent.com/20250664/34782209-fbe1e134-f5f5-11e7-9d9c-f15e88e2ee65.png)

**Comment by OctoPenguin** [comment] 2018-01-11 11:11
Let me show you what you have to do.
To start, go to Settings > Network > Proxies. Turn on manual proxy settings. Even if you don't have a proxy, add 127.0.0.1 to the Exceptions list and click save. You are done! You may have to restart for changes to take effect.

![applicationframehost_2018-01-11_13-10-07](https://user-images.githubusercontent.com/30018896/34822812-db34aee0-f6d0-11e7-859d-4a6b7495d119.png)

**Comment by OctoPenguin** [comment] 2018-01-16 13:56
Update: the proxy workaround no longer works on Mac

**Comment by chinners** [comment] 2018-01-17 11:01
I've started getting this error. The proxy fix didn't work for me (Win 10 32 bit).

I can resolve the issue by going into task manager and closing all Wordpress processes. Then I restart the app and it works fine. Bit strange, but might be a quick fix for some.

**Comment by 413x-4rtur0** [comment] 2018-01-22 09:53
![image](https://user-images.githubusercontent.com/22374817/35214737-29ef6324-ff30-11e7-9d77-f5b29839cb20.png)

maybe this is the answer.

**Comment by 413x-4rtur0** [comment] 2018-01-22 09:54
![image](https://user-images.githubusercontent.com/22374817/35214769-43b7fe38-ff30-11e7-8345-a2aa9bf9aeb0.png)
 maybe this can work.

**Comment by astralbodies** [comment] 2018-01-23 15:26
Can you all see if the current beta has the same issue? If you go into the app preferences/settings and change the release channel to beta you should get 3.2.0-beta2. Let me know!

**Comment by OctoPenguin** [comment] 2018-01-26 07:42
@astralbodies I'd love to help, but we can't actually _open_ the app due to this bug. If you wouldn't mind sending me the DEB file for the beta I'll check for you :)

**Comment by astralbodies** [comment] 2018-01-26 12:48
@OctoPenguin 🤦‍♂️ Sorry about that! I uploaded the binaries for 3.2.0-beta2 to this page on GitHub for you all to try out:

https://github.com/Automattic/wp-desktop/releases/tag/3.2.0-beta2

**Comment by Liandrina** [comment] 2018-01-27 03:02
Had the error last night.  Tried the above fix (proxy) nothing.  Changed to beta in settings and it seemed to work, but I think it was just a fluke because it didn't download the beta version.  Tried again tonight and it errors again.  Downloaded the beta, same issue.

**Comment by OctoPenguin** [comment] 2018-01-27 07:38
@astralbodies Yup, the error still occurs in 3.2.0 Beta. I like the face though!

**Comment by i10e** [comment] 2018-02-02 15:11
Workaround: give the app its own `$HOME`.  This is not a fix, but you may find it an adequate long-term workaround.

I'm running the beta (wordpress-com-3-2-0-beta2.deb at [releases](https://github.com/Automattic/wp-desktop/releases)) like this on Debian-based distributions:

`$ mkdir ~/wpcom-home  # first time`

`$ HOME=~/wpcom-home /usr/share/wpcom/wpcom  # each time you run wpcom`

Following links from the app to your browser still works, as long as the browser is already running.  If you launch a browser from `wpcom`, the browser will be in `wpcom`'s home, and will set up a new empty browser profile.

When the app gets a persistent error like "code 105", run it in a fresh home.  You can try keeping settings and cookies from under `.config` in the old home to save the time of setting them again, and this may also help you work out which part of the configuration is going wrong.

Can someone suggest how to do this on Windows and macOS, or a better way to do this with the deb?

[running the wordpress desktop app](https://modulatedincompetence.wordpress.com/2018/02/02/running-the-wordpress-desktop-app/)

**Comment by i10e** [comment] 2018-02-04 15:19
The error came back.  I'm getting the same error with versions from 2.0, but not version 1.2.5.  If you need to demonstrate the essential functions and look of the app, versions from 1.2.5 will do.

Early versions are available --- [releases on github, earlier](https://github.com/Automattic/wp-desktop/releases?after=v2.8.0-beta10) --- but not binaries.

updated: [more failures; earlier versions; recruitment easter egg](https://modulatedincompetence.wordpress.com/2018/02/02/running-the-wordpress-desktop-app/#more-failures)

**Comment by igladun** [comment] 2018-02-06 17:52
I had the same issue. After deleting the ~/Library/Application Support/WordPress.com  - everything works.
(macOS 10.13.3)

**Comment by igladun** [comment] 2018-02-06 17:56
I had the same issue. After deleting the ~/Library/Application Support/WordPress.com - it works.
(macOS 10.13.3 and WP 3.2.0 beta)

**Comment by abioneperhobby** [comment] 2018-02-13 08:42
same issue on windows 10,
installed 3.1,
got error code 105 splash screen,
uninstalled,
installed 3.2.0-beta2,
reached login area,
login works,
and then a different code 105 splash screen
![image](https://user-images.githubusercontent.com/2149815/36140619-259161f0-10a2-11e8-9800-91298f898a5e.png)

**Comment by LinuxfarmerHH** [comment] 2018-02-13 18:42
Wordpress 3.1.0
Ubuntu 17.10

Same problem, proxy workarounds did not help. No newer version available at the moment.

**Comment by fdf75** [comment] 2018-02-14 09:13
Check DNS. I resolved this way.

**Comment by OctoPenguin** [comment] 2018-02-15 13:22
@fdf75 I'm using Google Public DNS, so I wouldn't think that's a problem

**Comment by fdf75** [comment] 2018-02-15 14:33
I was using Google DNS too. When I have change with DNS of my internet provider error has gone.

**Comment by i10e** [comment] 2018-02-15 17:28
Thanks @fdf75 --- I was using Google DNS 8.8.8.8, and that fixed it for me too.

**Comment by LinuxfarmerHH** [comment] 2018-02-15 18:07
Where is a different DNS required? On the central router or the PC running the app?

**Comment by fdf75** [comment] 2018-02-15 18:59
On pc. I have simply set it on "Obtain DNS server address automatically"

**Comment by AfonsoGomes** [comment] 2018-02-15 20:46
Just to let yous know I just had the same issue with Google's DNS settings (8.8.8.8) and when changed to Open DNS it seemed to do the trick. Will continue to check to see if it was not a fluke.

**Comment by syntaxfx1** [comment] 2018-09-12 00:50
Adding to ChrissiePollock's post -  #1402670-zen - another code 105 error.  
I passed the following directly to WP helpdesk, but I'll copy it here.
I ran a traceroute to my website and got a warning that there was more than one address for the URL.
If the desktop app needs a single address and it picked the "wrong" one, I could see why it might think that there was a proxy issue.
So a question - is anyone else getting a warning from traceroute about multiple dresses for their URL?

**Comment by nsakaimbo** [comment] 2021-09-13 18:59
Update on this thread: we're closing this issue as we expect this and a whole host of other issues to be resolved by the new, re-architected version of the application that was just released. The latest build can now be downloaded at the WordPress Desktop landing page [here](https://apps.wordpress.com/desktop/) (please install version 7.2.0 or greater).

**Closed by nsakaimbo** 2021-09-13 18:59 UTC
Labels: [Type] Bug, OSS Citizen, [Pri] Normal
