### ISSUE TITLE
Export: Export media library is disabled and has uncaught error in the console

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-desktop#677] opened 2019-10-11 16:56 UTC
It looks like the "export media library" feature is not functional in the desktop app. It should be disabled with a feature flag or fixed to work in the app. cc @southp as I see you added this feature in https://github.com/Automattic/wp-calypso/pull/27581. (I'm not sure if this issue is new or if it wasn't tested earlier.)

#### Steps to reproduce
1. In the app, open the console (CTRL + SHIFT + i on macOS).
2. Go to My Sites > Export.

#### What I expected

I expect to be able to use any available export options.

#### What happened instead

The download button under "Export media library" is disabled and the console shows an uncaught error:

```
Uncaught Error: Given action "SET_MEDIA_EXPORT_DATA", reducer "mediaExportUrl" returned undefined. To ignore an action, you must explicitly return the previous state. If you want this reducer to hold no value, you can return null instead of undefined.
    at 241.js:33
    at combinedReducer (entry-main.js:12)
    at 241.js:33
    at combinedReducer (entry-main.js:12)
    at dispatch (241.js:33)
    at entry-main.js:1
    at entry-main.js:12
    at entry-main.js:12
    at entry-main.js:12
    at entry-main.js:12
```

#### App Version / OS version

WPDesktop 4.4.0-beta2 / macOS 10.15

#### Screenshot / Video

<img width="1307" alt="Screenshot 2019-10-11 17 49 38" src="https://user-images.githubusercontent.com/8658164/66669697-f21bf200-ec4f-11e9-90dc-0d201c9d375c.png">

#### Context / Source
#beta-testing

**Comment by southp** [comment] 2019-10-14 02:44
Thanks for tagging me. I'll take a look.

**Comment by southp** [comment] 2019-10-21 08:38
Update: 

* The endpoint is responding with the expected `media_export_url` field. However, somehow the data-layer is dispatching the SET_MEDIA_EXPORT_DATA action with the value `undefined`.
* I can't build the dev version of the desktop. It looks like updating `electron-builder` to 21.2 would help: https://github.com/electron-userland/electron-builder/issues/3990

I'll look a bit more tomorrow.

**Comment by southp** [comment] 2019-11-05 06:05
Progress updates:

@jsnajdr and @loremattei kindly helped me resolve the `npm install` issue with https://github.com/Automattic/wp-desktop/pull/694 . However, `make build` is still failing for me with the following error message:
```
• electron-builder version=20.32.0
  • loaded configuration file=package.json ("build" field)
  • electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies

To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
Error: Configuration is invalid.
 - configuration.mac should be one of these:
   object { appId?, artifactName?, asar?, asarUnpack?, binaries?, bundleShortVersion?, bundleVersion?, category?, compression?, cscInstallerKeyPassword?, cscInstallerLink?, cscKeyPassword?, cscLink?, detectUpdateChannel?, electronLanguages?, electronUpdaterCompatibility?, entitlements?, entitlementsInherit?, extendInfo?, extraDistFiles?, extraFiles?, extraResources?, fileAssociations?, files?, forceCodeSigning?, generateUpdatesFilesForAllChannels?, helperBundleId?, icon?, identity?, minimumSystemVersion?, protocols?, provisioningProfile?, publish?, releaseInfo?, requirements?, target?, type? } | {
     "type": "null"
   }
   Options related to how build macOS targets.

   Details:
    * configuration.mac has an unknown property 'hardenedRuntime'. These properties are valid:
      object { appId?, artifactName?, asar?, asarUnpack?, binaries?, bundleShortVersion?, bundleVersion?, category?, compression?, cscInstallerKeyPassword?, cscInstallerLink?, cscKeyPassword?, cscLink?, detectUpdateChannel?, electronLanguages?, electronUpdaterCompatibility?, entitlements?, entitlementsInherit?, extendInfo?, extraDistFiles?, extraFiles?, extraResources?, fileAssociations?, files?, forceCodeSigning?, generateUpdatesFilesForAllChannels?, helperBundleId?, icon?, identity?, minimumSystemVersion?, protocols?, provisioningProfile?, publish?, releaseInfo?, requirements?, target?, type? }
    * configuration.mac should be null:
      {
        "type": "null"
      }

How to fix:
1. Open https://electron.build/configuration/configuration
2. Search the option name on the page.
  * Not found? The option was deprecated or not exists (check spelling).
  * Found? Check that the option in the appropriate place. e.g. "title" only in the "dmg", not in the root.

    at validateConfig (/Users/southp/a8c/wp-desktop/node_modules/read-config-file/src/main.ts:133:19)
From previous event:
    at _validateConfig2 (/Users/southp/a8c/wp-desktop/node_modules/app-builder-lib/out/util/config.js:336:27)
    at validateConfig (/Users/southp/a8c/wp-desktop/node_modules/app-builder-lib/out/util/config.js:299:27)
    at /Users/southp/a8c/wp-desktop/node_modules/app-builder-lib/src/packager.ts:285:11
    at Generator.next (<anonymous>)
From previous event:
    at Packager._build (/Users/southp/a8c/wp-desktop/node_modules/app-builder-lib/src/packager.ts:284:133)
    at /Users/southp/a8c/wp-desktop/node_modules/app-builder-lib/src/packager.ts:280:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Packager.build (/Users/southp/a8c/wp-desktop/node_modules/app-builder-lib/src/packager.ts:237:14)
    at build (/Users/southp/a8c/wp-desktop/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/Users/southp/a8c/wp-desktop/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/Users/southp/a8c/wp-desktop/node_modules/electron-builder/src/cli/cli.ts:46:19)
```

On the current `develop` branch, running the dev version by `npm run dev` can't reproduce the bug. However, I can't be sure it has been fixed accidentally because the way it runs is quite different from a electron-bundled app. 

I'm out of time today so will dig more the next day.

**Comment by southp** [comment] 2019-12-18 03:53
At least on my computer, `wp-desktop` still doesn't seem to be buildable on OSX Catalina. Catalina has deprecated all the non-64bit binaries and the electron builder we are using now requiring `Mac::Memory` module which isn't compatible with 64bit perl. My assumption is that upgrading the whole electron stack might help, but I won't have reasonable bandwidth to explore this direction in a foreseeable future. 

Since I can't even start for such a long time, I'm unassigning myself from here to not stand in the way. If it still persists when the build on Catalina is fixed, I'll be more than happy to revisit.

**Comment by nsakaimbo** [comment] 2020-02-05 20:57
@southp Just an update that build issues on Catalina have been resolved on the tip of `develop` branch - we just upgraded Electron and core dependencies in #757.

You should be able to build and run the application now - let me know if you need any help/run into any issues.

**Comment by southp** [comment] 2020-02-13 03:35
Thanks for the heads up @nsakaimbo . I'll give it a spin in the near future.

**Comment by nsakaimbo** [comment] 2021-09-13 18:13
Update on this thread: we're closing this issue as we expect this and a whole host of other issues to be resolved by the new, re-architected version of the application that was just released. The latest build can now be downloaded at the WordPress Desktop landing page [here](https://apps.wordpress.com/desktop/) (please install version 7.2.0 or greater).

**Closed by nsakaimbo** 2021-09-13 18:13 UTC
Labels: [Type] Bug, [Pri] High
