### ISSUE TITLE
Editor: Error Code 310 When Writing Posts

### ISSUE THREAD

**Issue by druesome** [Automattic/wp-desktop#759] opened 2020-02-01 08:10 UTC
I get this error when I try to write a post using the app.

> Uh oh!
> 
> WordPress.com ran into an error! (code 310)

<img src="https://d.pr/i/v4i13D+" width="600" />

Seems to only happen on Atomic sites, not on Simple sites.

#### Steps to reproduce
1. Log into app
2. Select an AT site under My Sites
3. Click the Write button

#### What I expected

For the editor to open up in the app and let me write an article.

#### What happened instead

Editor struggles to open, ends up with the error above. A new tab in my browser loads with the editor open.

#### App Version / OS version

WordPress Desktop App version 4.7.0 / MacOS version 10.14.5

**Comment by samjhamdy** [comment] 2020-02-01 23:51
Also reported in https://mc.a8c.com/support-stats/happychat/transcript.php?id=18349539

**Comment by nsakaimbo** [comment] 2020-02-03 16:00
@druesome Thanks for reporting this issue. Can you confirm whether you have the Classic Editor enabled, or recently toggled this setting via WP Admin? Could you try flipping the Classic Editor toggle to the opposite value of it's current setting and seeing if this make a difference? (This isn't a fix, but might help us narrow down the root cause.)

Thanks!

**Comment by khristiansnyder** [comment] 2020-02-03 17:12
Another reported in 2685593-zen

**Comment by codebykat** [comment] 2020-02-03 18:58
Reposting this from @samjhamdy:

> Also reported in 18349539-hc

**Comment by joweber123** [comment] 2020-02-06 04:25
Another report here 2674964-zen.  It looks like for previous reports enabling the Classic Editor plugin in wp-admin causing this error to disappear.

**Comment by kathrynwp** [comment] 2020-02-17 21:34
Another report in 4703327-zen

Windows 10 build 19041.84 / app version 4.7.0

Toggling Classic Editor plugin on and off did not fix the error.

**Comment by kathrynwp** [comment] 2020-02-18 16:40
User above reports that activating the Classic editor allows them to post. 

Follow-up in 2725741-zen

**Comment by rachelmcr** [comment] 2020-02-19 12:31
I am consistently running into this error in WPDesktop v4.7.0 while trying to edit posts on any Jetpack-connected sites I've tested with Gutenberg enabled (and no recent changes to the editor selection for those sites). I don't get this error on WordPress.com Simple sites.

Network requests show many requests back and forth between `wp-login.php?action=jetpack-sso` (which ends up with a `result=success` parameter, redirecting it to `post.php`) and `post.php` (with a `reauth=1` parameter, which sends it back to `wp-login.php`). I can't seem to save the requests in a HAR file from the app, but I've saved the requests and the response headers for some of these requests if those details would be helpful to review.

I tried clearing the Gutenberg selection for one of the Jetpack sites, which allowed me to open a post in the Calypso classic editor in the app. I then enabled Gutenberg again (using the editor prompt in the app to try it) and it immediately triggered this 310 error again.

**Comment by rachelmcr** [comment] 2020-02-19 12:46
I manually installed v5.0.0-beta.2 side by side with v4.7.0 to test it. I opened the app v5.0.0-beta.2 (was already logged in) and was able to open posts from my Jetpack-connected sites in Gutenberg in the app there, with no other changes. It seems to be resolved in this version.

I then opened v4.7.0 to test there again and noticed I was logged out there. After logging in again, I didn't get the 310 error anymore but I did run into https://github.com/Automattic/wp-desktop/issues/697.

**Comment by rfmarves** [comment] 2020-02-28 01:13
I found his thread when I stumbled with the same issue.  Switching to the classic editor served as a good workaround to use the app.  If I switch back to the block editor, it starts getting the error again.

**Comment by nsakaimbo** [comment] 2020-02-28 15:25
Thanks for the report, @rfmarves. Can you confirm what version of the application you were using when you experienced the error?

**Comment by rfmarves** [comment] 2020-03-01 04:20
> Thanks for the report, @rfmarves. Can you confirm what version of the application you were using when you experienced the error?

I was using Wordpress Desktop version 4.7.0 for Windows.  Today I received the version 5.0.0 and after I installed it, the problem went away and it works well with the block editor now.

Thank you!

**Comment by nsakaimbo** [comment] 2020-04-02 14:05
Another report from user @jcrowson (thank you!), who is redirected to a browser (blank screen) when trying to edit a post. See description here:

`https://github.com/Automattic/wp-desktop/issues/827#issue-592639035`

This further confirms the issue is driven by toggling between Classic and Gutenberg editors.

@belcherj I'm going to try to debug this issue further but I think we need some help on the Calypso side of things to prioritize this.

**Comment by jcrowson** [comment] 2020-05-13 13:28
Is there any update to this? Or is there a way I can help solve it?

**Comment by jcrowson** [comment] 2020-06-16 09:34
@nsakaimbo @druesome I don't want to jinx it, but I think this is now working in the latest version (5.2.0).

What changed?

**Comment by nsakaimbo** [comment] 2021-06-30 18:21
Update on this thread: we're closing this issue as we expect this and a whole host of other issues to be resolved by the new version of the application (v7.0.5) that was just released. The latest build can now be downloaded at the WordPress Desktop landing page [here](P7jrAc-3-p2).

**Closed by nsakaimbo** 2021-06-30 18:21 UTC
Labels: Calypso [Pending], [Pri] High, [Type] Bug
