### ISSUE TITLE
macOS: Days stats showing blank on the app

### ISSUE THREAD

**Issue by vajrasar** [Automattic/wp-desktop#929] opened 2020-06-23 12:46 UTC
The user is facing an issue on the WordPress.com desktop app where they do not see "Days" stats.

Sometimes when they toggle between Week and Days - the Days stat restores and sometimes restarting fixes that. It's a hit-and-miss issue that happens at regular intervals but not always.

#### Steps to reproduce
We were not able to replicate it on our end.

#### App Version / OS version
OS X 10.15 and latest app version (as the user downloaded the app and installed in multiple times)

#### Screenshot / Video
![](https://razzmtazz.blog/wp-content/uploads/2020/06/Screen-Shot-on-2020-06-23-at-181017.png)

#### Context / Source
#3080986-zen

**Comment by vajrasar** [comment] 2020-06-23 12:46
@nsakaimbo do you have any pointers for the next steps of debugging?

**Comment by nsakaimbo** [comment] 2020-06-23 14:38
From what I see in the ticket, it appears this behavior is observed in both their browser and in the desktop app, is that correct? 

> The effect you see is the one I’m talking about but I’m getting it in the desktop app. I hadn’t realised I was also seeing it in Firefox. I wouldn’t normally check my stats in the browser, I nearly always use the desktop app for that.

If so, it seems there's likely an account-level issue at play.

Is the user's site simple or Atomic? Public or private? Any other pertinent details? Did you try to inspect/troubleshoot their domain info and/or Jetpack install? (Perhaps this is a Jetpack synchronization issue?)

Without a reliable repro it's hard to take an educated guess at the root cause - just suggesting some things to try.

**Comment by vajrasar** [comment] 2020-06-25 15:47
Hey, @nsakaimbo thanks for taking a look. The site is non-AT and the primary domain name info seems to be correct and valid. Is there still a chance of JP sync issues when the site is non-AT?

**Comment by rachelmcr** [comment] 2020-07-08 11:02
Since this isn't a desktop app bug, I'm going to close this issue.

@vajrasar I'd suggest following up on this as a Calypso issue. Since we haven't been able to reliably reproduce it, it will be hard to investigate it as a bug, so I'd suggest gathering more troubleshooting details with the user to get more information about what's happening when the issue occurs (perhaps checking the dev console for any JavaScript errors or network request errors/issues).

**Closed by rachelmcr** 2020-07-08 11:02 UTC
Labels: [Platform] macOS
