### ISSUE TITLE
Customize: Customizer fails to load

### ISSUE THREAD

**Issue by samiff** [Automattic/wp-desktop#504] opened 2018-09-21 00:54 UTC
## Expected
Click on `Customize` and load the customization options for a site.

## Actual
Customizer never loads and returns `Sorry, the customizing tools did not load correctly`. Sites in question can load Customizer fine in a web browser.

In JS console only errors I see are:

![console](https://user-images.githubusercontent.com/15803018/45854045-226fb600-bd06-11e8-997a-d40485bf86e7.PNG)

![capture](https://user-images.githubusercontent.com/15803018/45854055-34515900-bd06-11e8-8ba3-c17c38dfd6d0.PNG)

## Details
**App version**: 3.5.0 (also tried 3.6.0-beta1 release on Windows)
**macOS High Sierra** 10.13.6 (was fresh install)
**Windows 10 Pro** 17134.285 (was reinstallation)
**Site**: `free2319test.wordpress.com` (others fail as well)

1431566-zen

**Comment by rachelmcr** [comment] 2018-09-21 10:39
Thanks for the report!

I tested on several WordPress.com Simple sites on macOS 10.13.6, WPDesktop 3.6.0-beta1 and in each case the customizer opened as expected.

I then tested in a Windows 10 VM, with a fresh install of WPDesktop 3.5.0. I got inconsistent results there:

* The first time I tried to open the customizer, it failed to load.
* Subsequent attempts worked as expected, on that site and others.
* I restarted the app and the customizer continued to work as expected.
* I logged out and logged in to the same account again, and now the customizer fails to load every time on any site.

**Comment by sandymcfadden** [comment] 2018-10-11 11:13
Had an additional report from a customer of the same thing happening on Windows 10 in 1476398-zen

I tested on a Windows 7 computer and had the same issue on a test Simple Site. Here is a screenshot of the Console
<img width="390" alt="screen_shot_2018-10-11_at_8_10_48_am" src="https://user-images.githubusercontent.com/1326294/46800264-86960080-cd2d-11e8-9ddc-c044cc98e32c.png">

**Comment by JessBoctor** [comment] 2018-11-24 19:02
I have another user with a similar experience. 

They cannot open the Customizer and receive the 'Customizer did not load properly'. They have attempted 

- reloading the tools via the 'try again' button
-logging in and  out
-they have reinstalled the app
-they reverted the app to version 3.5

They are running the app on a Windows 10 64 bit machine

Here is a link to the Zendesk ticket: [https://woothemes.zendesk.com/agent/tickets/1588863](https://woothemes.zendesk.com/agent/tickets/1588863)

**Comment by Ferdev** [comment] 2018-11-28 19:20
Another customer is having the same issue on macOS.

reference: 1603969-zen

**Comment by KokkieH** [comment] 2019-01-08 10:03
Another report from the [forums](https://en.forums.wordpress.com/topic/i-cant-customize-my-blog-through-the-desktop-app/).

Happening in 3.8.0 in Windows, though I can also intermittently replicate on Mac OS.

Suggested they try restarting, rebooting router, flushing DNS cache for now.

**Comment by jsknight1969** [comment] 2019-01-20 15:58
I am having the same issue with Wordpress > 3.8 stable and beta.  I am running MacOS 10.14.2.  If I let the update to > 3.8 happen, after restart of the app, the customizer will not load.  I uninstall the app and reinstall 3.8, the issue is resolved.

**Comment by jonnyruzek** [comment] 2019-02-06 15:22
Another report on PC in the desktop app (and all browsers) in 1776517-zen.

**Comment by AMcGrady** [comment] 2019-04-11 18:53
Another report on PC using Desktop app 4.0 with Windows 10.

zd-1951469

**Comment by nsakaimbo** [comment] 2020-03-23 20:47
As of v5.0.0, the customizer seems to be redirecting to an external browser (and no longer even displays the "Sorry, the customizing tools did not load correctly" message as reported earlier).

Opened an issue against Calypso to track: Automattic/wp-calypso/issues/40377

**Comment by rachelmcr** [comment] 2020-03-24 15:26
@nsakaimbo It looks like you tested with a WordPress.com Atomic site, which I believe has different expected behavior in Calypso. If I understand correctly, the expectation is:

* WordPress.com Simple sites will open the customizer at https://wordpress.com/customize (embedded in Calypso).
* WordPress.com Atomic and regular Jetpack sites will open the customizer in WP Admin (`/wp-admin/customize.php`). These links will currently open outside the desktop app because they aren't within Calypso.

I think the main issue here is that https://wordpress.com/customize doesn't always load correctly when opening the customizer on a Simple site in the app.

**Comment by nsakaimbo** [comment] 2020-03-25 14:36
Thanks for the education here, @rachelmcr - good to know. The fact that there are differences in how simple vs. atomic sites are supposed to work hasn't quite sunk in yet. 😅 

To double-check, I just signed up for a new dummy account with the `wordpress.com` domain and launched my site. I signed into the Desktop application and attempted to access the customizer, and that appears to work as expected (i.e. customizer is displayed in the application).

That being said, the last update to this issue was in April 2019. Have you experienced this (or do you know if anyone that has) recently?

**Comment by rachelmcr** [comment] 2020-03-27 17:46
I can't reproduce this on Mac, but I can on a Windows 10 VM with WPDesktop 5.0.0.

I tried the same steps I used [before](https://github.com/Automattic/wp-desktop/issues/504#issuecomment-423490422). Although the customizer opened with no problems at first, I can consistently reproduce it this way:

> I logged out and logged in to the same account again, and now the customizer fails to load every time on any site.

Interestingly, I'm also seeing https://github.com/Automattic/wp-desktop/issues/317 at the same time. I wonder if the underlying issue is the same for both, and there's a problem with how I'm authenticated to my site, since both the stats sparkline image and the customizer are served from my site (the customizer is in an iframe in Calypso) instead of from Calypso directly.

**Comment by nsakaimbo** [comment] 2020-03-27 19:44
@rachelmcr Thanks for the tip! I initially didn't test this on Windows, but I attempted to repro based on your description and there's definitely some bugs here.

Steps:

Repeated trials of logging out and back in with same account:

- Clicking "My Site" immediately after logging back in redirected me to a browser(!). Subsequent clicks worked as expected. However I only observed this once.
- Accessing the customizer after logging back in does break frequently (but not always). It will hang for a while, and then eventually display `Sorry, the customizing tools did not load correctly` message.
- I did observe the "broken stats" link as well (about half the time)

Narrowing a repro down to login/logout is super helpful. Will keep poking at this further.

**Comment by rezzap** [comment] 2020-05-06 06:56
We have a user reporting this is happening now on a Mac. 

In WP app 5.0.1 on Windows 10 Pro 10.0.18362 Build 18362, the customizer now does load (it never used to before) but now the customizer fails to load with the same error message `Sorry, the customizing tools did not load correctly` in Mac OS 10.15.4 

I'm replicating the same issue with the customizer failing to load for a simple WordPress.com site in the app on Mac OS 10.15.3, running the WP desktop app 5.0.1. For a self-hosted or atomic site, the customizer redirects to the browser (I think that's always been the case).

Logging in and out doesn't fix this, nor does restarting the app. It also doesn't change if my site is private or public.

Reported in 2935597-zen

**Comment by donalirl** [comment] 2021-07-12 08:25
Occurred on Mac app version 7.0.6 on Mac OS 11.4.

**Comment by nsakaimbo** [comment] 2021-07-12 20:42
@donalirl Thanks for the report. Could you please confirm with the user:

(1) What type of site this is occurring with? (Simple, Atomic, self-hosted?)
(2) Is this a private site?
(3) Does this error also occur in a traditional browser?

**Comment by donalirl** [comment] 2021-07-13 05:24
Hi @nsakaimbo 

1. Site is a simple, WordPress.com hosted site. If needed, you can find their site details by visiting the chat reference and selecting Store Admin.
2. The site is public.
3. No, only in the app. Works fine in Safari browser.

**Comment by nsakaimbo** [comment] 2021-07-13 17:03
Thanks for the additional details, @donalirl. Could you please request logs from the user, if you haven't already? These can be exported via "Get Application Logs" under the "Help" menu.

**Comment by donalirl** [comment] 2021-07-14 05:16
Asking for the logs and to check security/firewall software and will report back.

**Comment by ersatzpenguin** [comment] 2021-07-14 13:40
> Asking for the logs and to check security/firewall software and will report back. #4137934-zen

@sandymcfadden and @nsakaimbo , the user has provided the requested logs and they're in the merge note on the interaction (second most recent note). If you're unable to access those, let me know and I can provide them another way.

**Comment by sandymcfadden** [comment] 2021-07-14 16:07
Thanks @ersatzpenguin I've reached out to the customer now as well to see if we can figure out what is happening.

**Comment by nsakaimbo** [comment] 2021-09-13 19:09
Update on this thread: we're closing this issue as we expect this and a whole host of other issues to be resolved by the new, re-architected version of the application that was just released. The latest build can now be downloaded at the WordPress Desktop landing page [here](https://apps.wordpress.com/desktop/) (please install version 7.2.0 or greater).

**Closed by nsakaimbo** 2021-09-13 19:09 UTC
Labels: [Type] Bug, OSS Citizen, [Pri] High, [Platform] Windows
