### ISSUE TITLE
Statuses are (still) not reflected correctly

### ISSUE THREAD

**Issue by BlameDutchie** [Automattic/wp-desktop#508] opened 2018-10-06 16:33 UTC
![wp-app-stupid](https://user-images.githubusercontent.com/12746371/46573479-da02fa00-c98d-11e8-8022-f2a524a5eea4.jpeg)

I think the image speaks for itself.

**Comment by rachelmcr** [comment] 2018-10-10 10:08
Thanks for the report! To confirm, is the problem that a post is incorrectly appearing in the Drafts list, or are those both drafts and the problem is that the drafts count is wrong? (We're tracking the latter issue here: https://github.com/Automattic/wp-desktop/issues/399)

**Comment by BlameDutchie** [comment] 2018-10-10 16:01
Hi Rachel,

Confirm: the draft count is wrong and also ... I have nothing in my Trash ;-)

**Comment by rachelmcr** [comment] 2018-10-10 16:03
Thanks for confirming. :) I'm going to go ahead and close this issue since it's being tracked in #399.

**Closed by rachelmcr** 2018-10-10 16:03 UTC
Labels: [Type] Bug
