### ISSUE TITLE
Linux: clicking on Preview opens about:blank

### ISSUE THREAD

**Issue by orschiro** [Automattic/wp-desktop#236] opened 2016-09-08 18:00 UTC
Dear all, 

Clicking on "Preview" opens an about:blank tab next to the previewed article tab.

Warmly,

-Robert

![image](https://cloud.githubusercontent.com/assets/170947/18360579/d9e5e968-75fe-11e6-8603-5488147e50e2.png)

![image](https://cloud.githubusercontent.com/assets/170947/18360585/ddcc2ea2-75fe-11e6-8ac6-8e486222c9ed.png)

**Comment by lancewillett** [comment] 2016-09-08 18:07
Hi Robert,
Can you please share more details? Browser version, OS, example URL, and steps to repeat it exactly. Thanks!

**Comment by orschiro** [comment] 2016-09-08 18:12
Hi Lance, 

of course!

- Ubuntu 16.04
- WordPress 1.6.0
- Latest Chromium browser

**Steps to reproduce:**

1. Create an article
2. Click on the preview button
3. The article preview should open in a new tab in your default browser
4. On my system it opens this additional blank tab

Maybe it's a local issue on my side?

-Robert

**Comment by nsakaimbo** [comment] 2020-02-21 20:40
Closing this issue as we have not been able to reproduce this since it was initially reported (confirmed the Preview buttons works as expected with Ubuntu 18.04 and v5.0.0-beta2). Please feel free to re-open if you're still experiencing this issue, or if it occurs again!

**Closed by nsakaimbo** 2020-02-21 20:40 UTC
Labels: OSS Citizen, [Type] Bug
