### ISSUE TITLE
Broken back button with block editor (Gutenberg)

### ISSUE THREAD

**Issue by sjaved87** [Automattic/wp-desktop#651] opened 2019-07-23 09:07 UTC
#### Steps to reproduce
1. Go to My Sites -> Site -> Posts
2. Add or edit an existing post
3. Click on the back button on top left-hand side

#### What I expected
It should return the user back to the previous page

#### What happened instead
It does nothing.

#### App Version / OS version
4.2.0
Mojave 10.14.5 (18F132)

#### Screenshot / Video
https://cld.wthms.co/e3HpLv

#### Context / Source

####Workaround for the issue I am facing is that:

Switch to the classic/old editor - screenshot -> https://cld.wthms.co/UGvpL7 -, click on the close button on the top left to go back to the previous page - screenshot -> https://cld.wthms.co/q7uqyi.

#### reported in #2200100-zen

**Comment by ivan-ottinger** [comment] 2019-07-23 13:11
User replied back sharing more info:

WordPress.com app version: 4.2.0
OS: Windows 10 (they say it is the latest version, but not much more info)

They also confirmed they are using Gutenberg and are editing existing post/page.

**Comment by kspilarski** [comment] 2019-07-23 15:12
Same issue here, with the user on **WordPress.com desktop app (4.2)**, and **Mojave 10.14**. 

- **Info:** 
In the desktop app, after publishing and/or updating the post, the left return arrow does not work and it's stuck in the same post. 

- **Follow-up ticket:** #2200927-zd 

<img width="811" alt="Blog+Posts+9+KP++WordPress com+2019-07-23+17-04-18" src="https://user-images.githubusercontent.com/36863633/61723702-df8ace80-ad6c-11e9-8af7-02c7e121df4d.png">

**Comment by zdenys** [comment] 2019-07-24 07:19
Another report  on `4.2` in 2202629-zen

**Comment by rachelmcr** [comment] 2019-07-26 12:54
I tested and reproduced the issue as described: the block editor back button doesn't do anything. It fails to close even if you try to close it immediately without making any changes.

I also opened the dev console (before opening the editor, using the shortcut `CTRL + SHIFT + i` on macOS) and the only error I see is when the editor first opens:

```
Failed to set referrer policy: The value 'strict-origin-when-cross-origin' is not one of 'no-referrer', 'no-referrer-when-downgrade', 'origin', 'origin-when-cross-origin', or 'unsafe-url'. The referrer policy has been left unchanged.
```

There are no other console errors or failed network requests when I click the back button to exit the editor.

I was able to exit the editor using the navigation in the `Window` dropdown menu, or using the shortcuts (e.g. `⌘ 1` to go to My Sites).

**Comment by rachelmcr** [comment] 2019-07-26 16:02
We just released a new beta version (4.3.0-beta2). I re-tested this issue in that version and can't reproduce it anymore with either creating or editing posts.

The issue will be resolved when 4.3.0 is released. Anyone who wants to try out the beta version can go to the app menu under WordPress.com > Preferences and select "Beta" for the Release Channel. Restarting the app will trigger an update to the beta version; please let us know if you still run into this in version 4.3.0-beta2 or after 4.3.0 is released.

**Comment by mdrockwell** [comment] 2019-07-30 12:17
Another report: 2197504-zen

**Comment by JessBoctor** [comment] 2019-07-30 16:38
Another report: 2205918-zen

**Comment by rachelmcr** [comment] 2019-07-30 17:52
@mdrockwell @JessBoctor did the workaround [mentioned above](https://github.com/Automattic/wp-desktop/issues/651#issuecomment-515439284) work for your users, or did trying out the latest beta version work for them? If not, it'd help to have more details about what they tried and what happened, to know if this issue requires more investigation.

**Comment by mdrockwell** [comment] 2019-08-01 21:13
> did the workaround [mentioned above](https://github.com/Automattic/wp-desktop/issues/651#issuecomment-515439284) work for your users, or did trying out the latest beta version work for them? If not, it'd help to have more details about what they tried and what happened, to know if this issue requires more investigation.

I didn't notice the workaround from the thread initially, but did see that there was a beta version of the app with the fix. I suggested the user manage their site from the browser until the update was released.

But I've since replied to the user suggesting they try the workaround for now.

**Comment by marcuswisecaesar** [comment] 2019-08-01 23:01
2197504-zd 

The user said they had been trying the workaround already.  I've asked for more clarification and thought I'd comment here.

**Comment by rachelmcr** [comment] 2019-08-12 08:52
I'm reopening this issue since the fix is still in beta (4.3.0 beta) and we're still getting new reports about it. Leaving the issue open will hopefully make it more discoverable if anyone else comes across this behavior in 4.2.0.

If anyone comes across this issue, there's no need to comment unless you've tried the 4.3.0 beta and this isn't resolved for you there (or you have other questions about this issue). Here are a couple available workarounds in the meantime:

* You can use the navigation in the `Window` dropdown menu, or using the shortcuts (e.g. `⌘ 1` to go to My Sites).
* You can try out the beta version by going to the app menu under WordPress.com > Preferences and selecting "Beta" for the Release Channel. Restarting the app will trigger an update to the beta version.

**Comment by Robertght** [comment] 2019-08-16 05:26
I confirm this issue being fixed in 4.3.0 beta2 and still a problem in 4.2.0. ref: #2276689-zen

**Comment by pauljacobson** [comment] 2019-08-27 05:45
I also encountered this issue in version 4.2.0 on a personal laptop running macOS High Sierra, v10.13.6.

**Comment by rachelmcr** [comment] 2019-08-27 09:36
Version 4.3.0 is now available — please update to that version and let us know if the problem comes back there.

**Closed by rachelmcr** 2019-08-27 09:36 UTC
Labels: [Platform] macOS, [Type] Bug
