### ISSUE TITLE
Get Apps: "Country Code" and "Phone Number" fields are inactive

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-desktop#855] opened 2020-04-21 05:28 UTC
Steps to reproduce:

1. Go to Account > Get Apps.
1. Try to select a country in the "Country Code" field.
1. Try to enter data into the "Phone Number" field.

**Result:** "Country Code" and "Phone Number" fields are inactive on the Get Apps page which prevents you from getting SMS message with a download link for the right app for your mobile device using the WPDesktop app.

<img width="1280" alt="Screen Shot 2020-04-20 at Apr 20 11 26 02 PM" src="https://user-images.githubusercontent.com/1119271/79828693-79b08f00-835e-11ea-88dc-79333640fc68.png">
<p style="clear:both;"><sup>Tested with WPDesktop 5.1.0-beta1 on macOS 10.14.6.</sup></p>

**Comment by rachelmcr** [comment] 2020-04-23 10:57
I can't reproduce this after logging in to an existing account in the app. Did you see this right after signup for a new account? If so, it's a result of the error reported in https://github.com/Automattic/wp-desktop/issues/655. (The app checks for an existing phone number in the account recovery settings and if it encounters that error then it can't load that field.)

What do you think of closing this issue and tracking everything in #655?

**Comment by nsakaimbo** [comment] 2021-09-13 17:32
Update on this thread: we're closing this issue as we expect this and a whole host of other issues to be resolved by the new, re-architected version of the application that was just released. The latest build can now be downloaded at the WordPress Desktop landing page [here](https://apps.wordpress.com/desktop/) (please install version 7.2.0 or greater).

**Closed by nsakaimbo** 2021-09-13 17:32 UTC
Labels: [Type] Bug, [Pri] Normal
