### ISSUE TITLE
Stuck on Tags thread with no exit (3.1.0 on OSX)

### ISSUE THREAD

**Issue by cecilearkay** [Automattic/wp-desktop#400] opened 2018-01-11 08:20 UTC
Hello, I'm using the WordPress.com app v3.1.0 on High Sierra (v10.13.2) and lately, I have been having trouble to access My Site.

When I open the app, it shows a tags thread from the Reader and there's no way to leave the page to access other areas of the app, such as My Sites. The links at the top of the app (WordPress.com / Start a blog / Sign in) open in the browser. Here's a GIF: http://cld.wthms.co/NdwjyS

Deleting the app and reinstalling it doesn't help. It opens at the same tags thread, so I'm guessing it much be cached somewhere on my computer.

**Comment by rachelmcr** [comment] 2018-01-16 10:00
Noting that this was also reported for 3.2.0-beta2 on Windows 10 in https://github.com/Automattic/wp-desktop/issues/401.

**Comment by cecilerainon** [comment] 2018-02-19 19:52
Today when trying to open the app (I'm still stuck as described initially), I got this error message. I'm not sure if it's related:

![capture d ecran 2018-02-19 a 12 01 52](https://user-images.githubusercontent.com/16645645/36394907-ade5a85e-15b6-11e8-81a1-f769ccdd6292.png)

**Comment by johngodley** [comment] 2018-03-05 12:43
@cecilerainon it doesn't look like you are logged in. I'm not sure how to get to this state. Could you open the app's dev tools (cmd+alt+i) and the refresh (cmd+r) and take a screenshot of any errors?

**Comment by cecilerainon** [comment] 2018-03-07 07:59
Just noting here that I talked to John and tried both _cmd+alt+i_ and _ctrl+shift+i_ and can't get the app's dev tools to show up.

**Comment by rachelmcr** [comment] 2018-10-17 09:47
I found one way to force this issue to reproduce:

1. Log in to the desktop app, and then close it.
2. In a web browser, log in to the same account.
3. Open the [Security > Connected Apps](https://wordpress.com/me/security/connected-applications) page.
4. Next to "WordPress.com Desktop App" select "Disconnect."
5. Open the desktop app again.

Result: You see a logged-out version of whatever screen you were last viewing in the desktop app. For example, I visited the [kittens Reader tag page](https://wordpress.com/tag/kittens) in the app, and after disconnecting the app I saw this logged-out version of that tag page:

![screenshot 2018-10-17 10 34 17](https://user-images.githubusercontent.com/8658164/47077161-3ec51c80-d1f8-11e8-8ea8-33fc91623b23.png)

To resolve the issue, I deleted the app and the following directories:
- `~/Library/Application Support/WordPress.com`
- `~/Library/Caches/com.automattic.wordpress`
- `~/Library/Saved Application State/com.automattic.wordpress.savedState`

Tested on macOS 10.13.6 with WPDesktop 3.6.0.

**Comment by cecilearkay** [comment] 2018-10-17 12:29
Thank you @rachelmcr, I didn't have anything in `Saved Application State` but it worked anyway! I'd reinstalled the app after months hoping it would update and it was unfortunately still the same problem. Fixed now! :)

**Comment by joweber123** [comment] 2018-11-26 12:33
I had a user report this same problem today using Windows 10.  I looks like @rachelmcr was able to fix this problem by removing the App and deleting some directories.  I would like to give this user some advice on how to proceed but do not have access to a Windows machine.  Could anyone help to advise what directories the user would need to delete on a Windows machine to get the App working correctly?

**Comment by rachelmcr** [comment] 2018-11-26 12:46
@joweber123 Windows should be a bit easier than Mac, in that using the Windows system "Add or Remove Software" should remove the files associated with the app. (I also learned we have instructions on [this app support page](https://apps.wordpress.com/support/#faq-desktop-8), including a script to help remove Mac files.)

If uninstalling and reinstalling like that doesn't resolve it on a Windows machine, let us know!

**Comment by pauljacobson** [comment] 2018-11-27 13:40
Hi @rachelmcr 

The user replied as follows:

>I had tried that before seeking help, but to no avail.
>On your advice I again tried that twice, restarted the computer before running the app, but the problem continues.

**Comment by liviopv** [comment] 2018-11-28 14:48
Sent the instructions above to the user.

**Comment by rachelmcr** [comment] 2019-02-21 10:33
As reported in https://github.com/Automattic/wp-desktop/issues/563, this issue has now gotten worse — it seems to happen every time with these steps (at least on macOS):

1. Open WordPress app on macOS
2. Navigate to any Tag view in Reader
3. Quit the app
4. Launch the app

**Comment by designsimply** [comment] 2019-02-26 16:46
Tested and confirmed using WPDesktop 4.0.0-beta1 on macOS 10.13.6 (username: `design5279`) that if you close the app while viewing a tags page that the app re-opens stuck in a logged out view of that page. I saw a few errors in the console but they don't appear to be related ([screenshot](https://user-images.githubusercontent.com/1119271/53369624-e0781b00-3908-11e9-830c-da10785712bd.png)).

I tested other types of pages in the Reader, and I found that a similar-ish problem happens if you browse to Reader > Search then close and re-open the app—except in that case closing and re-opening the app a 2nd time resolves the issue. ([1m17s](https://cloudup.com/cGGMBHZ9nXE))

I found that I could access the app again by closing the app, deleting `~/Library/Application\ Support/WordPress.com/settings.json` which contains a `last-location` setting which was pointing to a tag page, and re-opening the app and logging in again.

I can also confirm that `ctrl+shift+i` does not work from the logged out view ([screenshot](https://user-images.githubusercontent.com/1119271/53369623-e0781b00-3908-11e9-9b57-5ccc86dced43.png)).

**Comment by elibud** [comment] 2019-06-05 20:17
@belcherj not an urgent one, but can you look into this one at some point?

**Comment by belcherj** [comment] 2019-06-12 12:55
@elibud Will do!

**Comment by andreabadgley19** [comment] 2019-10-22 15:11
I'm so happy to find this issue reported! 😍 Thank you @cecilearkay ! I have been struggling with this on my desktop app for months and it was terribly frustrating. It is definitely still an issue. 

A WordPress.com customer reached out to support today about it in 16133963-hc. I tested the steps @rachelmcr provided [above](https://github.com/Automattic/wp-desktop/issues/400#issuecomment-430563819) and was able to get logged in again on my desktop app. I provided those same steps to the user in 2439577-zen. I have not received a reply yet on whether the steps were successful for them.

After testing, I also recommended that to avoid being stuck in the Tag view, they go to My Sites in the app before quitting the app. I was able to successfully reopen the app when I tested that flow.

**Comment by zdenys** [comment] 2019-10-25 10:27
I can replicate the issue with 4.5.0-beta1 on macOS Catalina 10.15. The odd thing is that I cannot seem to find any of the three folders:

```
~/Library/Application Support/WordPress.com
~/Library/Caches/com.automattic.wordpress
~/Library/Saved Application State/com.automattic.wordpress.savedState
```

Have they been moved to a different location?

**Comment by andreabadgley19** [comment] 2019-10-25 11:03
I only had this directory, which I found by searching "wordpress.com" in my finder:

> ~/Library/Application Support/WordPress.com

<img width="631" alt="desktop app directory" src="https://user-images.githubusercontent.com/56366469/67566263-59787e00-f6f5-11e9-905e-c3d041617b16.png">

I tested again just now. I got the app stuck on the Tag view again. Then, by deleting the app, deleting that directory, and then reinstalling the app I was able to log into the app successfully.

**Comment by rachelmcr** [comment] 2019-10-25 12:03
A direct way to get to each of these directories:

1. Open Finder.
2. Open the `Go` menu and select `Go to Folder` (or use the keyboard shortcut `Shift + Command + G`).
3. Paste in the full path (e.g. `~/Library/Application Support/WordPress.com`) or just `~/Library` to start from there, and press Go.

If deleting a single directory doesn't solve the problem for you or a user, please be sure to delete all of them. Deleting all of these supporting files should clear out everything app related so you can reinstall the app from scratch (as if it hadn't been installed before). This is, of course, just a workaround while the underlying issue is still present.

**Comment by andreabadgley19** [comment] 2019-10-25 12:04
Ahh, I didn't mention the other directories to the user since I didn't see them. Thank you for that tip, Rachel! I just responded to them with a screenshot. I'll tell them about the other directories as well since I neglected those in my first response.

**Comment by nsakaimbo** [comment] 2020-03-06 04:52
Hi, @derezion - Just tested on Ubuntu 18.04 and confirmed I'm able to uninstall the application just fine. (After quitting the application, right-click the icon to `Show Details`, and then select `Remove`.

<p align="center"> 
<img width="256" alt="ubuntu-right-click" src="https://user-images.githubusercontent.com/8979548/76053730-c584b180-5f33-11ea-8e71-137c4219ad27.png">
<img width="449" alt="ubuntu-uninstall" src="https://user-images.githubusercontent.com/8979548/76053731-c61d4800-5f33-11ea-83a4-df1c2c6bf840.png">
</p>

**Comment by derezion** [comment] 2020-03-20 00:44
Hello, @nsakaimbo . I tried those steps and couldn't uninstall the WordPress.com app even on my administrator account. I also tried `sudo apt remove wordpress` and that said wordpress wasn't installed.

**Comment by nsakaimbo** [comment] 2021-09-13 18:54
Update on this thread: we're closing this issue as we expect this and a whole host of other issues to be resolved by the new, re-architected version of the application that was just released. The latest build can now be downloaded at the WordPress Desktop landing page [here](https://apps.wordpress.com/desktop/) (please install version 7.2.0 or greater).

**Closed by nsakaimbo** 2021-09-13 18:54 UTC
Labels: [Type] Bug, [Pri] Normal
