### ISSUE TITLE
Block Editor: Closing and re-opening the app with the editor open leads to a login page

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-desktop#582] opened 2019-04-04 18:29 UTC
h/t @pauljacobson for the original report.

#### Steps to reproduce
1. Start and save a new post in the block editor.
2. Close the app with the editor still open.
3. Re-open the app.

#### What I expected

I expected the app to re-open with the editor still open to the post I was working on. (This is how the classic editor behaves in the app.)

#### What happened instead

I see a login page.

For a public site, I am taken to the regular Calypso login page (not the desktop-specific login page):

![Screenshot 2019-04-04 19 21 19](https://user-images.githubusercontent.com/8658164/55579201-9eb07080-570f-11e9-9313-e5168169dd41.png)

For a private site, I am taken to this private site login page:

![image](https://user-images.githubusercontent.com/8658164/55579251-b851b800-570f-11e9-828e-710ecf5ed4ba.png)

In addition, the app ends up in a half logged-in/logged-out state. You can use the links on those login pages to view the logged-out WordPress.com homepage and other logged out pages. You can use the Help button in the bottom right to access logged-in Calypso again, but even then trying to start a new post in the block editor leads to a login page.

#### App Version / OS version

WPDesktop 4.1.0-beta1

**Comment by rachelmcr** [comment] 2019-04-30 11:43
I ran into a new and exciting variation of this issue today:

1. Log out of the app.
2. Log in again.
3. Go to My Sites > Blog Posts.
4. Select a post to open in the block editor.

Result: It opens a login screen instead.

Quitting and restarting the app at any point seems to resolve the issue (i.e. quitting the app before logging in again prevents it from appearing, or quitting after you see the issue resolves it). But following the steps above without restarting the app consistently reproduces the issue for me, regardless of the site or post I choose.

**Comment by blowery** [comment] 2019-05-01 15:06
Seems like when we restore the app and try to load Gutenberg, we're using the same frame nonce every time instead of generating a new one...

**Comment by blowery** [comment] 2019-05-01 15:13
Looks like we may need to enhance https://github.com/Automattic/wp-calypso/blob/master/client/gutenberg/editor/calypsoify-iframe.tsx#L433 somehow.

**Comment by blowery** [comment] 2019-05-01 15:19
@rachelmcr's second repro seems to be a similar problem: a stale frame nonce.

**Comment by rachelmcr** [comment] 2019-07-07 15:26
This came up again in beta testing version 4.3.0-beta1 (h/t @thehenrybyrd, internal ref: p5T066-V5-p2). This can lead to some really bizarre and confusing user flows, depending on what steps you take once you hit that login screen.

**Comment by designsimply** [comment] 2019-07-10 23:26
I tried both sets of testing steps using WPDesktop 4.3.0-beta1 on macOS 10.14.5 and could only replicate the problem using the second set of steps.

### Test 1

> 1. Start and save a new post in the block editor.
> 2. Close the app with the editor still open.
> 3. Re-open the app.

Result: the app re-opened normally to editing a post if I closed and re-opened the app while the editor was open. ([24s](https://cloudup.com/ctvcMAGJATr))
<sup>Tested with WPDesktop 4.3.0-beta1 on macOS 10.14.5.</sup>

### Test 2

> 1. Log out of the app.
> 2. Log in again.
> 3. Go to My Sites > Blog Posts.
> 4. Select a post to open in the block editor.

Result: the app prompted me to log in after log out, log in, and trying to open a post. ([26s](https://cloudup.com/cu-J5Azt9_J))
<sup>Tested with WPDesktop 4.3.0-beta1 on macOS 10.14.5.</sup>

Full video for both tests: [5m16s](https://cloudup.com/c-L6kQhsJ_a).

**Comment by designsimply** [comment] 2019-07-10 23:27
Raising to high priority because it has come up in beta testing and because it leads to a broken flow when trying to edit content.

**Comment by zdenys** [comment] 2019-07-24 07:22
Another report on `4.2` in 2202629-zen

**Comment by designsimply** [comment] 2019-09-23 21:08
Re-tested with v4.3.0 and the problem is still happening that when you try to open a post with blocks after logging out and back in again you are prompted to log in when you are already logged in.

### Test 2

> 1. Log out of the app.
> 2. Log in again.
> 3. Go to My Sites > Blog Posts.
> 4. Select a post to open in the block editor.

Result: when a post with blocks is opened with the Desktop app after logging out and back in again, a login prompt appears when the block editor is expected. ([1m13s](https://cloudup.com/cyEYLoGpkZg))

Console error:

> Failed to fetch the user from /me endpoint: Error: An active access token must be used to query information about the current user. 
> at O (242.ced0120….min.js:51)
> 11.570c6dd….min.js:13 

<img src="https://user-images.githubusercontent.com/1119271/65462199-80037a80-de12-11e9-82e9-40a092760f16.png" width="660" alt="screenshot-showing-console-error-issue-582-wpdesktop-4 3 0">
<sup>Tested with WPDesktop 4.3.0 on macOS 10.14.6.</sup>

@mmtr, because this is labeled high priority, is this something you can help look into for the WPDesktop 4.4 release? cc @gwwar @loremattei

**Comment by nsakaimbo** [comment] 2021-06-30 18:22
Update on this thread: we're closing this issue as we expect this and a whole host of other issues to be resolved by the new version of the application (v7.0.5) that was just released. The latest build can now be downloaded at the WordPress Desktop landing page [here](P7jrAc-3-p2).

**Closed by nsakaimbo** 2021-06-30 18:22 UTC
Labels: [Pri] High, [Type] Bug
