### ISSUE TITLE
Cannot go back to the Login screen if user selects "Create account"

### ISSUE THREAD

**Issue by Tug** [Automattic/wp-desktop#659] opened 2019-08-21 14:01 UTC
Once you select "Create account" on the oauth login screen, you're redirected to this page that doesn't have a back button:

![image](https://user-images.githubusercontent.com/230230/63438199-377c2a00-c42c-11e9-9e36-622303e351da.png)

#### Steps to reproduce
1. Open the app
2. If logged in, log out
3. Click on "Create account"
4. Change your mind and log in => you cannot

#### What I expected
To have a button to go back to the login screen

#### What happened instead
I'm stuck in the sign up flow

#### Workaround
Quitting the app and opening it again brings me back to the login screen

#### App Version / OS version
Stable (tested on Mac OS, but probably not platform specific)

**Comment by designsimply** [comment] 2019-10-31 21:58
Tested and confirmed using WPDesktop 4.5.0-beta2 on macOS 10.14.6.

Adding a screenshot from WordPress.com on the web for comparison, which shows a different step 1 of 6 and also has a way to get back to the log in screen below the signup form (and of course you can also use the back button in a browser).

<img width="1280" alt="Screen Shot 2019-10-30 at Oct 30 8 16 49 AM" src="https://user-images.githubusercontent.com/1119271/67881874-ec0a8a00-fb06-11e9-8db0-ff7d8f382e4d.png">

**Comment by rachelmcr** [comment] 2019-11-12 12:56
This came up again in beta testing for WPDesktop 4.6.0-beta2, h/t @AmandaRiu .

cc @Automattic/zelda to consider when you work on cleaning up the `/desktop` signup flow. It looks like using `signup/onboarding-flow` will resolve this, as noted in Sheri's screenshot above.

**Comment by nsakaimbo** [comment] 2021-06-30 18:25
Update on this thread: we're closing this issue as we expect this and a whole host of other issues to be resolved by the new version of the application (v7.0.5) that was just released. The latest build can now be downloaded at the WordPress Desktop landing page [here](P7jrAc-3-p2).

**Closed by nsakaimbo** 2021-06-30 18:25 UTC
Labels: [Pri] Normal, [Type] Enhancement
