### ISSUE TITLE
v3.2.0 beta Desktop App - Markdown rendering

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-desktop#410] opened 2018-01-28 21:21 UTC
## What I expected

The App should render Markdown correctly as formatted HTML.

## Steps to reproduce

Writing Markdown text in the visual editor and publishing to a P2-powered site.

## What happened instead

Markdown rendering doesn't seem to be working. You can also see how the editor collapses line spacing between paragraphs even as it fails to properly render Markdown headings.

This is most apparent in a preview of the post (that fairly reflects how a published post is displayed):

![edit_post_ _paul_jacobson_s_p2_ _wordpress_com](https://user-images.githubusercontent.com/2912202/35487237-00cac4d2-0482-11e8-9f42-720d50e18a31.png)

**Comment by rachelmcr** [comment] 2018-01-29 10:33
Thanks for the report! I tested and couldn't reproduce this issue — I created a new post in the Mac desktop app (v. 3.2.0-beta2), wrote a new post with Markdown formatting, which was then rendered as expected in the post. I tried typing the Markdown in both the visual and HTML editors, and both worked for me.

Could you share more details about the steps you used to create the post? Also, can you confirm that "Use Markdown for posts and pages." is enabled under Settings > Writing in the site's WP Admin dashboard? Thanks!

**Comment by pauljacobson** [comment] 2018-01-31 06:11
Hi @rachelmcr 

I have the setting enabled. I suspect this may actually be an issue with the P2 theme that I'm using. I've noticed some odd behaviour with it lately. I'll ping you directly to discuss next steps.

**Comment by rachelmcr** [comment] 2018-01-31 11:33
Thanks! Based on what you've said I'm going to go ahead and close this issue, but if it ends up being a specifically desktop app issue we can reopen.

**Closed by rachelmcr** 2018-01-31 11:33 UTC
Labels: OSS Citizen
