### ISSUE TITLE
Typo in tar.gz for wordpress desktop app

### ISSUE THREAD

**Issue by WinstonPoh** [Automattic/wp-desktop#222] opened 2016-08-17 14:03 UTC
Original name: "**wordpress-com-linux-x64-1-4-0-tar.gz**". The "**-tar.gz**" causes problems extracting. Change to "**wordpress-com-linux-x64-1-4-0.tar.gz**" and it will work fine. My setup is Ubuntu 16.04, x64

**Comment by rachelmcr** [comment] 2016-09-06 14:37
Thanks for reporting this! I am going to close this issue, as it's a duplicate of this older report: https://github.com/Automattic/wp-desktop/issues/139

**Closed by rachelmcr** 2016-09-06 14:37 UTC
Labels: OSS Citizen, [Type] Bug
