### ISSUE TITLE
Maximized window bug

### ISSUE THREAD

**Issue by indig0F10w** [Automattic/wp-desktop#964] opened 2020-10-21 09:56 UTC
#### Steps to reproduce
1. Open Wordpress desktop
2. Maximize window by clicking titlebar or maximize button
3. Exit Wordpress desktop by File> Quit or by right-clicking system tray icon and Quit
4. Open Wordpress desktop nad the window is not maximized

#### What I expected
Wordpress desktop should remember window state

#### What happened instead
Wordpress desktop opens displaced top left

#### App Version / OS version
Wordpress desktop v6.0.3 (all v5 and v6 versions affected)
Windows 10 Enterprise 2004 19041.572

#### Screenshot / Video
![Awowp95Ze3](https://user-images.githubusercontent.com/17021548/96704209-1b5b7c00-1394-11eb-934d-82539acbaca7.gif)

**Comment by designsimply** [comment] 2020-10-22 17:42
I tested this based on your steps and I see what you mean. I tried the steps with a few other apps including Mail, File Explorer, and Internet Explorer and the size of the window was retained after opening, maximizing the app's size, closing, and reopening those apps. To be fair, I think it's an enhancement request and not a bug because it was probably never considered as something it should do and it's something that appears to be optional that an app can choose to support or not. In this case, it probably just wasn't considered before is all.

@nsakaimbo I also tested with Simplenote and the window size I changed to was retained after closing and reopening—do you think we could make it work that way for the WPDesktop app too?

**Comment by indig0F10w** [comment] 2020-10-22 17:51
Hello,

I consider this a bug because it is a Windows application and this behavior is not expected since Windows apps remember their window state on closing. At least all apps I use.

**Comment by indig0F10w** [comment] 2020-10-23 09:32
While searching thru Wordpress desktop logs to find any sensitive information to be removed before I send the logs I found this:

Settings:{"notification-badge":true,"notification-bounce":false,"release-channel":"stable","proxy-type":"","proxy-url":"socks5://localhost","proxy-port":"8080","proxy-pac":"","spellcheck-enabled":false,"wpDragAndDropDisabled":true,"last-location":"/plugins","win_tray":true,"window":{"x":-8,"y":-8,"width":1936,"height":1056}}

I will go out on a limb here and say that the window displacement is caused by "window":{"x":-8,"y":-8,".

Logs show that I have been using WP Desktop since 5.1.0 on this Windows install and that setting is stuck since then at least.

How did it get set up like that when users cannot set almost any options in WP Desktop and how do I fix it?

Thank you.

**Comment by indig0F10w** [comment] 2020-10-23 10:13
I deleted all settings from C:\Users\username\AppData\Roaming\WordPress.com\settings.json

Opened WP Desktop, set window to maximized, File > Quit.

Reopened WP Desktop, the settings came back with exact option as posted before.

Found out that I've been using WP Desktop since 4.3.0 on this install and it is installed for single user.

Completely removed WP Desktop, deleted all files, cleaned registry of Wordpress entries.

Reinstalled, restarted PC, opened WP Desktop, all my sites appeared after entering credentials, set window to maximized, File > Quit.

Again the settings came back and window is displaced x-8 y-8.

This is about all I can do, logs from clean install as single user sent to help@wordpress.com.

Thank you all very much for your time. Have a good day.

**Comment by nsakaimbo** [comment] 2020-10-23 18:20
Thanks for the detailed update, @indig0F10w - will take a look at your logs.

> How did it get set up like that when users cannot set almost any options in WP Desktop and how do I fix it?

The `settings.json` is intended to track internal state of the application, and not to be manipulated directly. That being said, it's very strange that deleting the file and re-starting the app didn't fix the issue - however that was an excellent step to try.

Quick question: did you by any chance - now or in the past - use an external monitor with your machine? Something similar happened to me with a different application on Windows 10 a while ago - once my monitor was disconnected, the application kept on opening offscreen (where the external monitor coordinates used to be!). Regardless, perhaps some of the steps recommended in this article might help:

https://www.technipages.com/bring-off-screen-window-back-onto-screen

`Fix 3 – Move Option 1`, `Fix 4 – Move Option 2` or `Fix 5 – Cascade Windows` might be particularly helpful.

Once the application is in view, it might help to drag the window slightly to help "reset" it's coordinates.

**Comment by indig0F10w** [comment] 2020-10-24 11:58
> Quick question: did you by any chance - now or in the past - use an external monitor with your machine?

I service equipment on a regular basis and rarely I have 2nd monitor. I usually connect mine to another computer until I set remote access.

For a fix scroll down to the facepalm part...

Installed a fresh copy of WP Desktop on virtual Windows 10 Pro. Entered my credentials, maximized and then Quit. The exact problem happens in virtual machine. On both installations WP Desktop now doesn't remember where I left off and starts in home of my so called blog. In settings.json the entry clearly says: "last-location":"/plugins/manage".

After opening settings.json with Notepad++ and just exiting with no edits made and no saving the file I started WP Desktop and now it always starts on plugins/manage. Now I think it may be something with permissions...

Fix 1: doesn't work
Slight change in displacement: "window":{"x":-7,"y":0
After changing resolution to monitor native 1920x1080 the settings revert back to: "window":{"x":-8,"y":-8

Fix 3: doesn't work
Moves WP Desktop window as it should. Left, center, right.
Interesting thing happens when I maximize it and move window to the right with Win+right arrow. Y coordinate always -8. The window now gets displaced: "window":{"x":952,"y":-8,

Tried all fixes from linked page, none works.

Facepalm inducing fix/workaround (as a non noob Windows user I wonder how did I miss this):
1. Right click Wordpress.com icon
2. Properties
3. Run: Maximized

Thank you very much for reading, I'm now going to live in a cave.

**Comment by nsakaimbo** [comment] 2020-10-28 15:01
Thanks for the update, @indig0F10w! Appreciate your due diligence and taking the time to post an update. The fact that this occurred in a Windows VM is an important data point - it almost seems like the specific VM implementation resolves absolute window coordinates differently than expected. 

> Thank you very much for reading, I'm now going to live in a cave.

No worries at all. In fact, thank YOU for your persistence, and for sharing for sharing the fix! This is worth making note of in case other users encounter something similar in the future. Also, 2020 has been a tough year for everyone - I think we can all relate to wanting to hide in a cave for a while. 😆

Cheers and thank you for using the WordPress Desktop application - please keep sharing any and all feedback!

**Comment by nsakaimbo** [comment] 2020-10-28 15:01
_Update_: closing as the user was able to resolve the issue.

**Closed by nsakaimbo** 2020-10-28 15:01 UTC
Labels: OSS Citizen, [Platform] Windows, [Pri] Low, [Type] Enhancement
