### ISSUE TITLE
v2.9.0 build, WordPress.com ran into an error "Cannot find module '../screen'" and "TypeError"

### ISSUE THREAD

**Issue by ehti** [Automattic/wp-desktop#339] opened 2017-10-13 00:39 UTC
User reported in #731031-zen that they're getting the following error when opening the app:

<img src="https://user-images.githubusercontent.com/6505293/31525292-ab456e70-afd8-11e7-94d5-135b09f86c7f.jpg" height="400">

I was able to replicate it on Windows 10, latest creators update and latest WP app build (2.9.0).

To replicate:
1. Open the app, it might open fine
2. Click the close button, it'll go to tray
3. Double-click the app icon on desktop (not on tray), the error should show up

Also, I ran into the "TypeError" below when I was trying to close + quit (from tray) and then relaunching the app a few times. This error showed up after about 4-5 such quits/re-opens:

<img src="https://user-images.githubusercontent.com/6505293/31525179-d11e49b0-afd7-11e7-9ce3-ba91223ebe49.jpg" width="500">

**Comment by rachelmcr** [comment] 2017-10-13 10:49
Noting @Tug's findings here:

> Seems relevant: https://github.com/electron/electron/issues/8862

> So I guess `app.exit()` instead here https://github.com/Automattic/wp-desktop/blob/develop/desktop/lib/app-instance/index.js#L34

**Comment by gemmagarner** [comment] 2017-10-18 12:02
Another report in #740787-zen

**Comment by gemmagarner** [comment] 2017-10-18 12:05
#879939-f (a fresh install of 2.9.0 fixed the issue).

**Comment by gemmagarner** [comment] 2017-10-18 12:30
Reported in #740984-zen

**Comment by Tug** [comment] 2017-10-18 12:42
I could not reproduce the issue using the `master` branch on macos. I tried launching the app twice but didn't get any error (the second process stopped and made the first window appear again.
So it seems to be limited to windows...

**Comment by GeoJunkie** [comment] 2017-10-18 15:17
Reported in 739615-zen . User tried uninstall/reinstall twice without success.

**Comment by gemmagarner** [comment] 2017-10-20 11:33
Reported in 743022-zen (they can use the app after closing the message).

**Comment by Lochlaer** [comment] 2017-10-24 14:22
Another user is reporting a similar/not quite _exactly_ the same error in 753355-zen:

![wordperss error](https://user-images.githubusercontent.com/6569475/31948533-cb153402-b89c-11e7-9758-7a714b59bda2.JPG)

I've asked them to uninstall and then reinstall the app, and am also asking for specific details of their PC.

**Comment by Lochlaer** [comment] 2017-10-25 01:14
One more report here in 754366-zen. Error message:

![screenshot 2017-10-24 15 56 05](https://user-images.githubusercontent.com/6569475/31975583-dd4c4fa6-b8f7-11e7-9415-a1536b96aabb.png)

**Comment by carladoria** [comment] 2017-10-25 19:58
Another report in [834410-zen](https://mc.a8c.com/support-stats/happychat/transcript.php?id=834410) in Windows 10
![app-sign-in-error](https://user-images.githubusercontent.com/23703267/32020176-4f2428d8-b99d-11e7-8efa-eeca08b914ca.png)

**Comment by gemmagarner** [comment] 2017-10-26 10:06
Another report in 882043-f

**Comment by brbrr** [comment] 2017-10-26 13:47
another report in ticket 756985

**Comment by kriskarkoski** [comment] 2017-10-26 14:41
Another report in 756655-zen

**Comment by astralbodies** [comment] 2017-10-31 19:25
This is resolved in 2.9.1 for Windows users. Thanks for all of the reports!

**Closed by astralbodies** 2017-10-31 19:25 UTC
Labels: [Type] Bug
