### ISSUE TITLE
Customizer fails to load, opens in browser window

### ISSUE THREAD

**Issue by tryptc** [Automattic/wp-desktop#359] opened 2017-11-11 20:17 UTC
The customizer fails to load, and opens in a browser window.

**Comment by rachelmcr** [comment] 2017-11-13 10:08
@tryptc Thanks for the report! I tested the following steps on two WordPress.com simple sites (one public and one private):

1. Open the desktop app.
2. Go to My Sites.
3. Select the site I want to customize and click the Customize button.

In both cases, the customizer successfully loaded in the app.

At this point, since I can't reproduce the issue and we don't have any additional detail, I'm going to close this issue. If the problem continues, it would help to know more about it, such as:

- Does it happen on any site you test?
- Does it happen consistently (every time you try to open the customizer) on the site?
- Does it only happen in the app, or also in a browser?
- Are there any console errors when it happens? (On a Mac, you can use CTRL+SHIFT+i to open the console.)

**Closed by rachelmcr** 2017-11-13 10:08 UTC
Labels: OSS Citizen
