### ISSUE TITLE
MacOS: The scroll resets to top once a block is being added or typed into

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-desktop#674] opened 2019-09-29 05:58 UTC
#### Steps to reproduce
1. Create a post with content which would generate a scroll bar.
2. Once done, try to add a block.
3. Either trying to add a block or type into one, will jump you to the top of the post

The problem is not present in the Classic mode.

Tested on my Simple site as well with Gutenberg Enabled

#### What I expected
To be able to see what I'm typing

#### What happened instead
It jumped me to the top of the post everytim

#### App Version / OS version
4.3.0 / macOS 10.14.6

#### Screenshot / Video
https://monosnap.com/file/l0HrxRpTbF7I8ocGQrcQAVXGl2JWUm

#### Context / Source
#user-report

**Comment by ewolput** [comment] 2019-09-29 12:30
I have exactly the same problem. The classic editor works fine. In a browser I have no problem. In the app with the block editor it jumps to the top.

**Comment by kosiew** [comment] 2019-09-30 04:16
Encountered the same issue at #2387887-zen

**Comment by retnonindya** [comment] 2019-10-01 09:21
Report: #2390258-zen

**Comment by rachelmcr** [comment] 2019-10-02 16:07
Thanks for the report! I confirmed this is still happening with the newest beta (version 4.4.0-beta1) on macOS 10.14.6, so it wasn't resolved with the latest Calypso version, and it is specific to the desktop app.

I also noticed that the screen returns to the top after any key press, even if it doesn't enter text into the editor, for example pressing the `shift` key. The block selection doesn't change, so I can continue to type into a block at the bottom of the editor, but it always immediately jumps to the top of the editor screen.

**Comment by thesacredpath** [comment] 2019-10-02 21:40
This is also happening in 4.3 on Win 10. Hoping that a fix makes it way into 4.4 for this. This user interested in trying public beta when it is available.

#15679759-hc
#2394986-zen

**Comment by rachelmcr** [comment] 2019-10-03 11:02
I did some additional testing and confirmed that this only happens on WordPress.com Simple sites, not Atomic or Jetpack sites.

The timing and behavior suggests that this is due to changes made in Gutenberg version 6.6, although since it only happens in the app it's likely something specific to how Electron handles the new Gutenberg behavior. I've asked for some investigation by developers who know Gutenberg and Electron to see if we can identify the cause. (Internal ref: p5T066-10s-p2)

**Comment by tanjoymor** [comment] 2019-10-10 04:17
I had disregarded this report on a case I was investigating, because my user wasn't using the app (they use a browser)... but at the same time, the issue described above sounds exactly the same as what my user reported as happening in a browser. I've requested more information from them. #2411476-zen

**Comment by rachelmcr** [comment] 2019-10-21 13:26
This issue is very similar to the issue reported to Gutenberg here: https://github.com/WordPress/gutenberg/issues/17255

That issue is now resolved, and I tested again with a WordPress.com Simple site and confirmed I am no longer seeing this issue in the app. (Tested on macOS 10.15 / WPDesktop 4.4.0.)

I am going to close this issue as it looks like that fix also fixed the problem we were seeing in the app. Please let us know if anyone reports this issue again!

**Comment by wpericam** [comment] 2019-10-24 03:14
> I had disregarded this report on a case I was investigating, because my user wasn't using the app (they use a browser)... but at the same time, the issue described above sounds exactly the same as what my user reported as happening in a browser. I've requested more information from them. #2411476-zen

This report has been resolved as the fix here seems to have worked for this user. 2439961-zd

**Comment by rezzap** [comment] 2019-11-14 15:47
Re-opening this issue as I've been able to replicate this again in the MacOS 10.15.1/ WPDesktop 4.5 and also reported by a user on the latest version of the Windows app (Windows 10 Home). 

Reported by user in 2489285-zen 

As soon as you try typing in a block to edit the content they get jumped right to the top. This does not replicate in the browser version of the site, but only on both apps in multiple posts. Only replicated on posts where the scroll bar is present in Gutenberg.

This was done on atomic site v2, WordPress.com.

Screenrecording: https://cl.ly/be4c58700271

**Comment by rachelmcr** [comment] 2019-11-14 16:36
Thanks @rezzap! I confirmed I can reproduce it in the current beta (WPDesktop 4.6.0-beta1) on macOS 10.15 with an Atomic WordPress.com site, but I can't reproduce it on a Simple site.

I also tested with a Jetpack site running WordPress 5.3 and I can reproduce it there. However, when I enable the Gutenberg plugin (to test the latest beta updates in Gutenberg) the issue is resolved.

It looks like there is a fix for this on WordPress.com and in the Gutenberg beta, but the fix isn't yet available in WordPress 5.3 or on Atomic sites. @rezzap one interim solution for the user who reported this is to enable the Gutenberg plugin (with the caveat that it's a beta plugin), but eventually that fix should be fully released.

**Comment by rachelmcr** [comment] 2019-11-14 16:38
@kwight my understanding was that the fix for https://github.com/WordPress/gutenberg/issues/17255 was included in WordPress 5.3, and it seemed to be fixed on WordPress.com after we merged the Gutenberg 6.6 release. Do you have any idea why this would still be an issue for Atomic sites and self-hosted sites on WordPress 5.3?

**Comment by gwwar** [comment] 2019-11-16 01:34
I think there are new reports in the 5.3 release https://github.com/WordPress/gutenberg/issues/18546

**Comment by allykmyta** [comment] 2019-11-23 22:30
Another report here: #2513318-zen

**Comment by rachelmcr** [comment] 2020-02-19 13:14
I tested this again in WPDesktop 5.0.0-beta.2 with a WordPress.com Simple site, a WordPress.com Atomic site, and a Jetpack-connected site running WordPress 5.3.2. I couldn't reproduce the issue any longer, so I'll close this as resolved.

**Closed by rachelmcr** 2020-02-19 13:14 UTC
Labels: [Type] Bug
