### ISSUE TITLE
Rendering crashes (Electron segfault) under Arch Linux

### ISSUE THREAD

**Issue by icaroperseo** [Automattic/wp-desktop#189] opened 2016-05-23 15:28 UTC
Currently I am presenting this issue:

![wordpress_desktop-electron](https://cloud.githubusercontent.com/assets/2342151/15475653/be80344a-20d0-11e6-9888-1e9adb78b0ce.jpeg)

and the cause could be the following: [Rendering crashes (white screen) when FontAwesome is used (Archlinux)](https://github.com/electron/electron/issues/4513)

Is there any possibility to solve this situation?

Thanks in advance!

**Comment by sendhil** [comment] 2016-05-24 07:42
Hi @icaroperseo - could you provide reproduction steps?

**Comment by icaroperseo** [comment] 2016-05-24 18:29
@sendhil Sorry for my mess! Here mi answer: https://github.com/Automattic/wp-desktop/issues/191#issuecomment-221360961

**Comment by rachelmcr** [comment] 2017-02-08 09:54
Closing as a duplicate of https://github.com/Automattic/wp-desktop/issues/191.

**Closed by rachelmcr** 2017-02-08 09:54 UTC
Labels: OSS Citizen

**Comment by icaroperseo** [comment] 2017-02-08 17:16
It seems since **wp-desktop** version **2.2.0** this issue no longer exist.

**Comment by rachelmcr** [comment] 2017-02-08 17:38
Thanks for letting us know!
