### ISSUE TITLE
WP Desktop App Error: 105!

### ISSUE THREAD

**Issue by jeremyb1** [Automattic/wp-desktop#407] opened 2018-01-27 05:59 UTC
Hi there!

Unfortunately I do not have more information than this right now from a user:

<blockquote>I am on a paid account and am trying to use the wordpress app in windows 10 to 
create a child theme, among other things. I am receiving 'Wordpress.com ran 
into an error! (code 105). I have tried uninstalling and reinstalling. I have 
changed settings from stable to beta to test if it happened with 3.2.0-beta2 
release- same issue. I have tried to add 127.0.0.1 to the proxy to no avail 
(as per the github recommendations)</blockquote>

I am getting more information but this is what I have in the meantime.

I don't have access to all of GitHub so I wasn't able to look farther [than this search](https://github.com/Automattic/wp-desktop/issues/334), which brought a similar issue and there was no solution there either.

Thanks!

**Comment by OctoPenguin** [comment] 2018-01-27 07:19
Hello! Thank you for sharing this with the team which I am not a part of! Although the issue you searched for does not have a solution, it is the main and current one which has been assigned to an actual developer.
While there is no solution, a workaround which is a little hit-or-miss has been come up with. This workaround is to add the IP address 127.0.0.1 to the proxy server exclusions list even if you have no proxy. See [this screenshot](https://user-images.githubusercontent.com/30018896/34822812-db34aee0-f6d0-11e7-859d-4a6b7495d119.png) for details on how to do this on Windows 10.

**Comment by brbrr** [comment] 2018-01-28 04:47
Hi @jburciaga0, Thanks for reporting this issue.

Just to confirm: You able to login without any issues, and 105 Error appears only when you trying to install child theme?

Looks like #334 it is the similar issue. Have you tried to restart your computer after setting proxy exclusions?

May I ask you to provide the exact steps to reproduce this issue?

**Comment by nsakaimbo** [comment] 2020-02-20 16:28
There have been no updates since this was first reported. Unclear if the recommended solution ultimately addressed the user's issue, and there have been no similar reports since. Closing for the time being (but please feel free to re-open if still relevant).

**Closed by nsakaimbo** 2020-02-20 16:28 UTC
Labels: OSS Citizen, [Type] Bug
