### ISSUE TITLE
Post editor menu out of place

### ISSUE THREAD

**Issue by lizkarkoski** [Automattic/wp-desktop#368] opened 2017-11-16 16:32 UTC
Windows 10 x64.
Same issue on version 3.1.0 beta 2

User report came from the forums at: http://en.forums.wordpress.com/topic/layout-issue-in-desktop-application-v-300

The settings menu is also unresponsive.

Issue is isolated to desktop app and user does not have these same issues via browser.

**Comment by designsimply** [comment] 2017-11-17 02:11
Copy of the screenshot from the person reporting the issue for reference:

![screenshot-wordpress-3-1-0-beta-2](https://user-images.githubusercontent.com/1119271/32925887-93f824a8-cb01-11e7-8f97-456f814067f9.png)

**Comment by rachelmcr** [comment] 2017-11-21 18:06
I can't reproduce this issue in stable version 3.0.0 or in 3.1.0-beta3, on Win10, with my account language set to Polish.

Looking at the user's screenshot, I'm also seeing another issue with the post settings underline (it's rounded instead of straight) that was resolved in Calypso in July in https://github.com/Automattic/wp-calypso/pull/16350 (which should have been included in WPDesktop 2.8.0 or maybe 2.9.0). This makes me think something may have gone wrong when the user tried to install the latest version of the app over an older version.

@lizkarkoski could you ask the user to try deleting the app and installing a fresh version from apps.wordpress.com? Since we can't reproduce the issue I'm going to close this but we can revisit if the problem persists on a clean install.

**Closed by rachelmcr** 2017-11-21 18:06 UTC
Labels: [Pri] BLOCKER, [Type] Bug
