### ISSUE TITLE
WordPress.com ran into an error

### ISSUE THREAD

**Issue by boostmoth** [Automattic/wp-desktop#284] opened 2017-04-04 01:22 UTC
A user forwarded us this crash report. No other information. See ticket 3141595

![image001](https://cloud.githubusercontent.com/assets/26887976/24638048/748a15b4-189a-11e7-9bea-64111439229f.jpg)

**Comment by spen** [comment] 2017-04-04 02:13
Seems to relate to #248

**Comment by designsimply** [comment] 2017-04-04 13:38
Thank you for the report! 

Closing this one as a duplicate of #248.

**Closed by designsimply** 2017-04-04 13:38 UTC
Labels: OSS Citizen
