### ISSUE TITLE
Back button not working when editing a page using the block editor

### ISSUE THREAD

**Issue by eoinsav** [Automattic/wp-desktop#657] opened 2019-08-10 17:35 UTC
The back button doesn't work when editing a page using the block editor.

#### Steps to reproduce
1. Open the desktop app and navigate to Pages.
2. Click in to edit a page with the block editor.
3. Try to leave the page by clicking the `<` button in the top left corner.
4. Nothing happens.

#### What I expected
To be able to leave the page and got back to the dashboard.

#### What happened instead
I can't leave the page.

#### App Version / OS version
WordPress.com Version 4.2.0 / iOS Version 10.14.6

#### Screenshot / Video
https://cld.wthms.co/RqCS3U

#### Context / Source
#user-report - 14126814-hc

**Comment by rachelmcr** [comment] 2019-08-12 08:48
Thanks for the report! This is a duplicate of https://github.com/Automattic/wp-desktop/issues/651 and is resolved in version 4.3.0 (currently in beta). There are a couple workarounds mentioned in that issue in the meantime:

* You can use the navigation in the `Window` dropdown menu, or using the shortcuts (e.g. `⌘ 1` to go to My Sites).
* You can try out the beta version by going to the app menu under WordPress.com > Preferences and selecting "Beta" for the Release Channel. Restarting the app will trigger an update to the beta version.

**Closed by rachelmcr** 2019-08-12 08:48 UTC
Labels: [Platform] macOS, [Type] Bug
