### ISSUE TITLE
Site Setup List: "An error occurred while fetching your account recovery settings" appears twice in the "Get the WordPress app" step

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-desktop#853] opened 2020-04-21 05:11 UTC
Steps to reproduce:

1. Sign up for a new account using the WPDesktop app.
1. Follow the Site Setup List steps until you reach the "Get the WordPress app" step.
1. Click the "Download mobile app" button.

**Result:** after clicking the "Download mobile app" button in the Site Setup List, "An error occurred while fetching your account recovery settings" appears twice. 

**Note:** if you browse to the Get Apps page directly in the app, the error only appears once so something in this particular flow is triggering it to appear twice.

![get-apps-error](https://user-images.githubusercontent.com/1119271/79827253-196c1e00-835b-11ea-8a51-0d0ebbaa7010.png)
<p style="clear:both;"><sup>Tested with WPDesktop 5.1.0-beta1 on macOS 10.14.6.</sup></p>

From the Network tap in developer tools:

* Request URL: https://public-api.wordpress.com/rest/v1.1/me/account-recovery
* Response: {"error":"unauthorized_client","message":"Your client is not permitted to access this resource."}
* Request Headers:
```:authority: public-api.wordpress.com
:method: GET
:path: /rest/v1.1/me/account-recovery
:scheme: https
accept: */json,*/*
accept-encoding: gzip, deflate, br
accept-language: en-US
authorization: Bearer *** REDACTED ***
origin: http://127.0.0.1:41050
referer: http://127.0.0.1:41050/
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) WordPressDesktop/5.1.0-beta1 Chrome/69.0.3497.128 Electron/4.2.12 Safari/537.36```

**Comment by rachelmcr** [comment] 2020-04-21 06:48
This looks like a duplicate of #655, although it sounds like the behavior has changed (error showing twice).

**Closed** 2020-04-21 06:48 UTC
Labels: [Pri] High, [Type] Bug
