### ISSUE TITLE
Windows icon is not hidpi

### ISSUE THREAD

**Issue by jkudish** [Automattic/wp-desktop#155] opened 2016-04-12 18:00 UTC
I've been playing around with the Windows app and one thing that I noticed is that the icon is a little bit fuzzy on a hidpi display.

**Comment by jasmussen** [comment] 2016-04-13 07:48
I think I know what this is, and if it is, it's out of our hands.

If it's related to the icon in the taskbar, there's a confirmed bug in Windows 10 which scales down non-Windows Store apps making them look fuzzy. But it only happens when you use the small taskbar. Compare:

![app-icon](https://cloud.githubusercontent.com/assets/1204802/14486278/4282e952-015c-11e6-8ddd-b9dbb98e603a.png)

![app-tile](https://cloud.githubusercontent.com/assets/1204802/14486284/452305b6-015c-11e6-842c-f37148a53437.png)

![taskbar](https://cloud.githubusercontent.com/assets/1204802/14486288/480aa978-015c-11e6-9c27-25536ebaac4f.png)

The 3rd icon is fuzzy, because it's a 32px version that's scaled down to 24px. <a href="https://social.msdn.microsoft.com/Forums/windowsserver/en-US/6c00a205-b08f-4f29-bf9e-c84fbb13f506/create-icons-for-windows-10-taskbar#b6820a36-25ff-4bd4-89cb-9f9c7aa242c9">The bug</a> is that it Windows 10 should be using the 24px version we supply in the .ico file. The issue is the same on hi-dpi displays, where a 64px icon will be scaled down to 48px, instead of the 48px version supplied by the icon file being used. I've reached out to Microsoft, and confirmed that this will be fixed in the Windows 10 anniversary update out this summer.

If it's related to the tray icon, <a href="https://github.com/electron/electron/issues/2248#issuecomment-161232671">this is a bug in electron itself</a>. You can't provide multi-resolution icons to the tray icon, basically. So you can either provide an icon that looks good _only_ on a 1x display, OR an icon that looks good _only_ on a 2x display. We picked 1x for the time being, as there are most users of such displays:

![tray](https://cloud.githubusercontent.com/assets/1204802/14486397/d4a1a3b4-015c-11e6-8eb2-662c05c96404.png)

<img width="221" alt="tray-hires" src="https://cloud.githubusercontent.com/assets/1204802/14486400/d7c0b0a8-015c-11e6-90d8-c4657bb9c444.png">

**Comment by jkudish** [comment] 2016-04-13 18:32
Wow, sounds like you did your research @jasmussen I'm impressed :smile: 

I meant the one in the taskbar, and I believe you there's a bug, but somehow other apps (slack, phpStorm, atom, etc.) that were definitely not from the Windows store have non-fuzzy icons for me. 

I didn't notice the tray icon yet, but that seems like a fair tradeoff for now

**Comment by jasmussen** [comment] 2016-04-13 18:37
:) I went down the rabbit hole. I can't stand fuzzy pixels!

> I meant the one in the taskbar, and I believe you there's a bug, but somehow other apps (slack, phpStorm, atom, etc.) that were definitely not from the Windows store have non-fuzzy icons for me.

Yep, I still think that's the bug that will be fixed come summer, because the .ico file used has all the densities I think it could ever need:

![screen shot 2016-04-13 at 20 34 55](https://cloud.githubusercontent.com/assets/1204802/14504948/4214c246-01b7-11e6-8737-827d3b3d20cf.png)

I think fuzziness can be more pronounced in some graphics than others. In our case, when the thin W shape is scaled down, it becomes extra blurry. Were it bolder perhaps it wouldn't looks so bad.

It's a doozy of a Windows bug, though — I think in some situations the icon will look crisp when in the taskbar, so long as it's *not pinned*. Haven't verified this, but it's a weird one.

**Comment by jasmussen** [comment] 2016-04-18 10:11
Closing this for now. We can reopen if new information comes to light.

**Closed by jasmussen** 2016-04-18 10:11 UTC
Labels: [Type] Bug
