### ISSUE TITLE
Problem upgrading on macOS Sierra

### ISSUE THREAD

**Issue by khurtwilliams** [Automattic/wp-desktop#250] opened 2016-11-10 16:14 UTC
Upon launch, the app shows a notification that an update is avaiable. Once I click the *Update & Restart* button, the  app exits, restarts, and I get the same notificaiton. The app is never updated. Manually downloading and instaling is the only workable option.

I am currently using WordPress 1.8.0 on macOS Sierra version 10.12.1 (16B2555)

![screen shot 2016-11-10 at 11 09 59 am](https://cloud.githubusercontent.com/assets/686971/20184473/cd849372-a736-11e6-97d9-19d6dbc731e0.jpg)

**Comment by rachelmcr** [comment] 2016-12-01 12:33
Thanks for reporting this, @khurtwilliams! Did this also happen to you on the latest update to version 2.0.0?

I haven't reproduced this issue on Mac OS Sierra (10.12.1), on updates for either the beta or stable channels. @sendhil what could cause a failure to update like this?

**Comment by khurtwilliams** [comment] 2016-12-06 03:06
I have the latest macOS Sierra build. The only way to update the software
is a manual download and install. The updater service is stuck in a loop.


From: Rachel McR. <notifications@github.com> <notifications@github.com>
Reply: Automattic/wp-desktop
<reply@reply.github.com>
<reply@reply.github.com>
Date: December 1, 2016 at 07:33:16
To: Automattic/wp-desktop <wp-desktop@noreply.github.com>
<wp-desktop@noreply.github.com>
CC: Khürt Williams <khurtwilliams@gmail.com> <khurtwilliams@gmail.com>,
Mention <mention@noreply.github.com> <mention@noreply.github.com>
Subject:  Re: [Automattic/wp-desktop] Problem upgrading on macOS Sierra
(#250)

Thanks for reporting this, @khurtwilliams <https://github.com/khurtwilliams>!

**Comment by khurtwilliams** [comment] 2017-02-01 17:26
Any update on this, @sendhil ?

**Comment by sendhil** [comment] 2017-02-01 23:29
Hi @khurtwilliams - could you try deleting the app and re-installing it fresh and when the next update hits let me know if it's still an issue?

**Comment by khurtwilliams** [comment] 2017-02-02 00:35
I don't have access to the old version. If I uninstall I'll be reinstalling
the latest version. I won't be a able to test until the version after that.

https://islandinthenet.com

"Those that prosper consistently will think deeply, reevaluate, adapt,
and continually
evolve”. ~ Farnam Street

From: Sendhil Panchadsaram <notifications@github.com>
<notifications@github.com>
Reply: Automattic/wp-desktop
<reply@reply.github.com>
<reply@reply.github.com>
Date: February 1, 2017 at 18:29:57
To: Automattic/wp-desktop <wp-desktop@noreply.github.com>
<wp-desktop@noreply.github.com>
CC: Khürt Williams <khurtwilliams@gmail.com> <khurtwilliams@gmail.com>,
Mention <mention@noreply.github.com> <mention@noreply.github.com>
Subject:  Re: [Automattic/wp-desktop] Problem upgrading on macOS Sierra
(#250)

Hi @khurtwilliams <https://github.com/khurtwilliams> - could you try

**Comment by khurtwilliams** [comment] 2017-02-03 00:06
Here are some screen shots (and a short video) showing what happens when I tried updating form WordPress Desktop 2.0 to 2.2.0 on my iMac runnind macOS Sierra 10.12.13

![screen shot 2017-02-02 at 6 52 53 pm](https://cloud.githubusercontent.com/assets/686971/22574015/1d117722-e97a-11e6-99d0-33141c033f4b.jpg)

![screen shot 2017-02-02 at 6 53 20 pm](https://cloud.githubusercontent.com/assets/686971/22574088/a7f991c6-e97a-11e6-9019-ebea13ad782b.jpg)

Video: https://youtu.be/GFD2CfvSKgM

**Comment by khurtwilliams** [comment] 2017-02-03 00:07
@sendhil when is the next update? A week from now? Two week? 6 months? a year?

**Comment by ty-newton** [comment] 2017-05-01 02:30
This is also a problem for me.  I login as a non-admin user and when the WordPress application tries to update it fails silently; then wants to do the update again the next time I start the application.  In other applications I get a dialog asking me for an admin users credentials.  

When I do a clean install of the application I drag the WordPress icon onto the Applications folder icon.  The operating system pops up a dialog and asks me to authenticate as an administrator; then copies WordPress into my Applications folder.  Perhaps the updater also needs some logic to elevate privileges so the update can replace the files in the Applications folder.

**Comment by spencerberry** [comment] 2018-10-16 20:38
Another report came into live chat today for this issue.

User is on app version 3.5.0, Mac OS is 10.13.6 and has experienced this issue for many years, with around 3 years worth of app usage.

**Comment by tbradsha** [comment] 2019-01-25 18:18
I started on the Stable channel (3.8.0) and switched to Beta in the Preferences. This detected the newer version (3.9.0-beta2) and prompts to "Update & Restart". Choosing this option closes the app but didn't update and again prompted to "Update & Restart". After several tries, it did update.

I'm on macOS 10.14.3 (Mojave).

**Comment by khurtwilliams** [comment] 2019-02-02 14:42
The problem has persisted for years. I stopped using the WordPress app on macOS Mojave (10.14.2 (18C54)).

**Comment by rachelmcr** [comment] 2019-02-25 12:09
Our current hypothesis is that macOS puts the app in quarantine, and due to the way the quarantine works, the update may fail depending on timing. This is difficult to verify but seems to match the testing we've done. If that hypothesis is correct, then the update may fail if you hit the update button just after the update message pops up, but it should work if you wait long enough that the app's binary file is downloaded before hitting the button.

We are planning to notarize the app (see https://github.com/Automattic/wp-desktop/issues/548), which would prevent it from being sent to quarantine in the first place. If our hypothesis is correct, this will resolve the problem.

**Comment by KristinaKay** [comment] 2019-05-15 14:35
This is still a problem as of today. I was unable to update my Mac Desktop app. I have to download and overwrite the app.

**Comment by tecumsa** [comment] 2019-12-10 23:44
Pardon if this has been asked before, but why not just make it available in the AppStore? Then Apple handles the updates.

**Comment by rachelmcr** [comment] 2019-12-11 10:59
@tecumsa Thanks for the question! When we considered submitting the app to the Mac App Store in the past, it didn't fit with all of Apple's policies so it wasn't allowed. It was decided as of https://github.com/Automattic/wp-desktop/issues/108 to not go that route and it likely still wouldn't be accepted. Although that past decision doesn't preclude us exploring that option in the future, it isn't a quick fix for this issue.

**Closed** 2020-06-23 16:13 UTC
Labels: OSS Citizen, [Platform] macOS, [Pri] High, [Type] Bug
