### ISSUE TITLE
Mac Desktop App Freezing on write click in editor

### ISSUE THREAD

**Issue by code4copy** [Automattic/wp-desktop#264] opened 2017-02-02 17:19 UTC
On mac book, app is freezing when right click on editor, need to restart app.

**Comment by lancewillett** [comment] 2017-02-03 17:22
Hello, could you please add your OS version and app version? Thank you. Does uninstalling and re-installing the app fix the problem?

**Comment by rachelmcr** [comment] 2017-02-08 09:52
This is a known issue that we're tracking here: https://github.com/Automattic/wp-desktop/issues/241

I'm going to close this issue since it's a duplicate of the one above. Thanks for reporting it!

**Closed by rachelmcr** 2017-02-08 09:52 UTC
Labels: OSS Citizen
