### ISSUE TITLE
Customizer returns error on Mac

### ISSUE THREAD

**Issue by eurello** [Automattic/wp-desktop#280] opened 2017-03-20 05:30 UTC
1. Install most recent version of Desktop app
2. Launch app, go to My Sites, choose a site
3. Click Customize 
4. See this error: 

<img width="580" alt="screen shot 2017-03-20 at 1 23 27 pm" src="https://cloud.githubusercontent.com/assets/8698879/24089400/349ebfec-0d71-11e7-9d40-8928ab37354f.png">

Sierra 10.12.3, error persists whether proxied or not. 

Reported by user, reference # 3116931

**Comment by menakas** [comment] 2017-03-20 07:05
Another instance of the same error reported: (Internal reference # 3117459-t) , though on Windows

**Comment by sandymcfadden** [comment] 2017-03-20 19:06
I'm getting the same thing as well. Using a fresh install of the app on Windows 7 Professional. 

I managed to get a screenshot with the console open hopefully the errors in there will help. They disappeared quickly.
<img width="957" alt="windows-app-error" src="https://cloud.githubusercontent.com/assets/1326294/24116925/06f35f9c-0d87-11e7-82bd-661f3960f7cf.png">

I also noticed when clicking the Using a Proxy link it took me to a page which only explained how to bypass the proxy on a Mac even though I was in the Windows app.

**Comment by menakas** [comment] 2017-03-21 06:13
Another instance in live chat (Internal reference **256625-hc** )

**Comment by sandymcfadden** [comment] 2017-03-22 00:33
Not 100% sure this is related but had a report from a user on Windows 10 that when ever they open the customizer the app crashes and they receive this error message.
![40976dc7ebe6416c9713fdc38b11dad6](https://cloud.githubusercontent.com/assets/1326294/24176918/ea31a574-0e7d-11e7-88a2-24e5056dc735.png)

Reference #3114196-t

**Comment by astralbodies** [comment] 2017-03-22 11:59
I recently compiled (a week ago) the desktop app based off of wp-calypso master and I'm getting this when trying to load the customizer:
![2017-03-22_06-58-29](https://cloud.githubusercontent.com/assets/373903/24196778/0c913ffe-0ecd-11e7-85e3-37a9de4a6d09.png)

**Comment by astralbodies** [comment] 2017-03-22 18:17
Just got current on wp-calypso on another desktop build and I am getting the error & visual reported with the issue rather than the Sorry Drake.

**Comment by astralbodies** [comment] 2017-03-22 18:24
Confirmed the same thing happens on Windows 10 with desktop 2.3.0-beta2.

**Comment by Lochlaer** [comment] 2017-03-31 01:00
Another user reported this in #3132459-t while using the app in his iMac, and I was able to reproduce on my own in my MacBook Air. I tried closing the app and then re-opening it, and got this:

![screen shot 2017-03-30 at 19 58 15](https://cloud.githubusercontent.com/assets/6569475/24532094/548b7d58-1583-11e7-881f-12dd8efc016d.png)

I clicked on the RETURN HOME button and was able to get back to the Reader.

**Comment by Lochlaer** [comment] 2017-04-02 22:52
Another user is reporting the same issue in #3135020-t. Windows app. 

![83c7192188d7436c8e9a9a62ada00477](https://cloud.githubusercontent.com/assets/6569475/24591678/eb39fcac-17cc-11e7-8c68-bd2415035030.png)

**Comment by designsimply** [comment] 2017-04-03 22:29
Tested and confirmed using WP Desktop 2.3.0-beta3 (unproxied).

![screen shot 2017-04-03 at mon apr 3 4 28 43 pm](https://cloud.githubusercontent.com/assets/1119271/24634332/9f129f0a-188a-11e7-9fd8-a09d146beb63.png)

Also spotted a console error on the error page:

> GET https://s0.wp.com/wp-content/mu-plugins/emoji/twemoji/svg/1f615.svg 404 ()
> failed-to-start.html:23

**Comment by sirbrillig** [comment] 2017-04-14 19:40
Like @sandymcfadden above, I was able to quickly grab a screenshot of the errors before the site crashes. 

Notable things:

- The Customizer actually loads in its iframe (at least the controls panel).
- We get a CSP "frame-ancestors" violation (cc @mattwiebe who was working on this recently).

<img width="1389" alt="screen shot 2017-04-14 at 3 35 01 pm" src="https://cloud.githubusercontent.com/assets/2036909/25053892/2237335a-2128-11e7-9e60-c6b2b90c2f1c.png">

Hopefully fixing the CSP (which was introduced in WP 4.7) will resolve this issue.

**Comment by sirbrillig** [comment] 2017-04-14 21:01
Looks like the URL is `http://127.0.0.1:41050` (from [here](https://github.com/Automattic/wp-desktop/blob/723281efbf80113cf70c1a11db2d217f7f2c56ad/public_desktop/failed-to-start.html#L27)). I added that to the allowed frame-ancestors, and it looks like that solves the issue!

**Comment by sirbrillig** [comment] 2017-04-14 21:05
@designsimply I created a separate issue (#288) for the broken icon error you saw.

@Lochlaer I think that the reloading "page not found" might be separate. If it's still unresolved, could you create another issue for it?

**Comment by sirbrillig** [comment] 2017-04-14 21:06
Marking this as closed, but let me know if there's further issues!

**Closed by sirbrillig** 2017-04-14 21:06 UTC
Labels: [Type] Bug
